(function(global){
  const VERBS=[
    {type:'irregular',forms:["be","was / were","been"],decoys:["beed","wased","beened"],regularizationDecoys:["been","were"],irregularDecoys:[]},
    {type:'irregular',forms:["beat","beat","beaten"],decoys:["beated","beatten","beatened"],regularizationDecoys:[],irregularDecoys:[]},
    {type:'irregular',forms:["become","became","become"],decoys:["becomed","becomed","becamed"],regularizationDecoys:["becomed"],irregularDecoys:[]},
    {type:'irregular',forms:["begin","began","begun"],decoys:["begined","beginned","begunned"],regularizationDecoys:["begined"],irregularDecoys:[]},
    {type:'irregular',forms:["bend","bent","bent"],decoys:["bended","bented","benten"],regularizationDecoys:["bended"],irregularDecoys:[]},
    {type:'irregular',forms:["bet","bet","bet"],decoys:["betted","betten","bett"],regularizationDecoys:["betted"],irregularDecoys:[]},
    {type:'irregular',forms:["bite","bit","bitten"],decoys:["bited","biten","bitted"],regularizationDecoys:["bited"],irregularDecoys:[]},
    {type:'irregular',forms:["bleed","bled","bled"],decoys:["bleeded","bleeded","bleden"],regularizationDecoys:["bleeded"],irregularDecoys:[]},
    {type:'irregular',forms:["blow","blew","blown"],decoys:["blowed","blewen","blowned"],regularizationDecoys:["blowed"],irregularDecoys:[]},
    {type:'irregular',forms:["break","broke","broken"],decoys:["breaked","broked","brocken"],regularizationDecoys:["breaked"],irregularDecoys:[]},
    {type:'irregular',forms:["breed","bred","bred"],decoys:["breeded","breden","bredd"],regularizationDecoys:["breeded"],irregularDecoys:[]},
    {type:'irregular',forms:["bring","brought","brought"],decoys:["bringed","brang","broughten"],regularizationDecoys:["bringed"],irregularDecoys:["brang"]},
    {type:'irregular',forms:["build","built","built"],decoys:["builded","builted","builden"],regularizationDecoys:["builded"],irregularDecoys:[]},
    {type:'irregular',forms:["burst","burst","burst"],decoys:["bursted","bursten","bursed"],regularizationDecoys:["bursted"],irregularDecoys:[]},
    {type:'irregular',forms:["buy","bought","bought"],decoys:["buyed","boughten","baught"],regularizationDecoys:["buyed"],irregularDecoys:[]},
    {type:'irregular',forms:["catch","caught","caught"],decoys:["catched","caughten","cought"],regularizationDecoys:["catched"],irregularDecoys:[]},
    {type:'irregular',forms:["choose","chose","chosen"],decoys:["choosed","chosed","chosened"],regularizationDecoys:["choosed"],irregularDecoys:[]},
    {type:'irregular',forms:["come","came","come"],decoys:["comed","camed","commen"],regularizationDecoys:["comed"],irregularDecoys:[]},
    {type:'irregular',forms:["cost","cost","cost"],decoys:["costed","costen","costt"],regularizationDecoys:["costed"],irregularDecoys:[]},
    {type:'irregular',forms:["creep","crept","crept"],decoys:["creeped","crepten","crepped"],regularizationDecoys:["creeped"],irregularDecoys:[]},
    {type:'irregular',forms:["cut","cut","cut"],decoys:["cutted","cutten","cutt"],regularizationDecoys:["cutted"],irregularDecoys:[]},
    {type:'irregular',forms:["deal","dealt","dealt"],decoys:["dealed","dealten","dealedt"],regularizationDecoys:["dealed"],irregularDecoys:[]},
    {type:'irregular',forms:["dig","dug","dug"],decoys:["digged","duggen","dag"],regularizationDecoys:["digged"],irregularDecoys:["dag"]},
    {type:'irregular',forms:["do","did","done"],decoys:["doed","didone","doned"],regularizationDecoys:["doed"],irregularDecoys:[]},
    {type:'irregular',forms:["draw","drew","drawn"],decoys:["drawed","drewed","drawen"],regularizationDecoys:["drawed"],irregularDecoys:[]},
    {type:'irregular',forms:["drink","drank","drunk"],decoys:["drinked","dranked","drunken"],regularizationDecoys:["drinked"],irregularDecoys:[]},
    {type:'irregular',forms:["drive","drove","driven"],decoys:["drived","droven","drivened"],regularizationDecoys:["drived"],irregularDecoys:[]},
    {type:'irregular',forms:["eat","ate","eaten"],decoys:["eated","ated","eatten"],regularizationDecoys:["eated"],irregularDecoys:[]},
    {type:'irregular',forms:["fall","fell","fallen"],decoys:["falled","felled","fallened"],regularizationDecoys:["falled"],irregularDecoys:[]},
    {type:'irregular',forms:["feed","fed","fed"],decoys:["feeded","feden","fedd"],regularizationDecoys:["feeded"],irregularDecoys:[]},
    {type:'irregular',forms:["feel","felt","felt"],decoys:["feeled","felten","feeld"],regularizationDecoys:["feeled"],irregularDecoys:[]},
    {type:'irregular',forms:["fight","fought","fought"],decoys:["fighted","foughten","faught"],regularizationDecoys:["fighted"],irregularDecoys:[]},
    {type:'irregular',forms:["find","found","found"],decoys:["finded","founded","founden"],regularizationDecoys:["finded"],irregularDecoys:[]},
    {type:'irregular',forms:["fit","fit","fit"],decoys:["fited","fitteded","fitten"],regularizationDecoys:["fited"],irregularDecoys:[]},
    {type:'irregular',forms:["fly","flew","flown"],decoys:["flied","flyed","flowed"],regularizationDecoys:["flyed"],irregularDecoys:["flied"]},
    {type:'irregular',forms:["forbid","forbade","forbidden"],decoys:["forbidded","forbided","forbiddened"],regularizationDecoys:["forbidded"],irregularDecoys:[]},
    {type:'irregular',forms:["forget","forgot","forgotten"],decoys:["forgetted","forgotted","forgotened"],regularizationDecoys:["forgetted"],irregularDecoys:[]},
    {type:'irregular',forms:["forgive","forgave","forgiven"],decoys:["forgived","forgaven","forgivened"],regularizationDecoys:["forgived"],irregularDecoys:[]},
    {type:'irregular',forms:["freeze","froze","frozen"],decoys:["freezed","frozed","frozened"],regularizationDecoys:["freezed"],irregularDecoys:[]},
    {type:'irregular',forms:["get","got","gotten"],decoys:["getted","getten","goted"],regularizationDecoys:["getted"],irregularDecoys:[]},
    {type:'irregular',forms:["give","gave","given"],decoys:["gived","gaven","givened"],regularizationDecoys:["gived"],irregularDecoys:[]},
    {type:'regular',forms:["ask","asked","asked"],irregularDecoys:["askt","asken","osk"],spellingDecoys:["askked","askeded"]},
    {type:'regular',forms:["call","called","called"],irregularDecoys:["coll","callt","culled"],spellingDecoys:["caled","calleded"]},
    {type:'regular',forms:["change","changed","changed"],irregularDecoys:["chung","changen","chought"],spellingDecoys:["changeed","changd"]},
    {type:'regular',forms:["clean","cleaned","cleaned"],irregularDecoys:["clan","clent","clown"],spellingDecoys:["cleand","cleaneded"]},
    {type:'regular',forms:["close","closed","closed"],irregularDecoys:["cloze","clost","closen"],spellingDecoys:["closeed","closd"]},
    {type:'regular',forms:["cook","cooked","cooked"],irregularDecoys:["cack","coken","coakt"],spellingDecoys:["cookked","cookt"]},
    {type:'regular',forms:["dance","danced","danced"],irregularDecoys:["dunce","dant","dancen"],spellingDecoys:["danceed","dancd"]},
    {type:'regular',forms:["help","helped","helped"],irregularDecoys:["halp","helpt","holpen"],spellingDecoys:["helpd","helpped"]},
    {type:'regular',forms:["jump","jumped","jumped"],irregularDecoys:["jamp","jumpt","jumpen"],spellingDecoys:["jumpd","jumpped"]},
    {type:'regular',forms:["like","liked","liked"],irregularDecoys:["loke","liken","laught"],spellingDecoys:["likeed","likd"]},
    {type:'regular',forms:["live","lived","lived"],irregularDecoys:["lave","loven","livt"],spellingDecoys:["liveed","livd"]},
    {type:'regular',forms:["look","looked","looked"],irregularDecoys:["lak","looken","laught"],spellingDecoys:["lookd","lookked"]},
    {type:'regular',forms:["move","moved","moved"],irregularDecoys:["mave","moven","mought"],spellingDecoys:["moveed","movd"]},
    {type:'regular',forms:["open","opened","opened"],irregularDecoys:["opan","opent","upen"],spellingDecoys:["openned","opend"]},
    {type:'regular',forms:["play","played","played"],irregularDecoys:["plew","plown","plaid"],spellingDecoys:["plaied","playd"]},
    {type:'regular',forms:["start","started","started"],irregularDecoys:["stort","sturt","starten"],spellingDecoys:["startted","startd"]},
    {type:'regular',forms:["study","studied","studied"],irregularDecoys:["stode","studen","stud"],spellingDecoys:["studyed","studid"]},
    {type:'regular',forms:["stop","stopped","stopped"],irregularDecoys:["stup","stopen","stopt"],spellingDecoys:["stoped","stoppd"]},
    {type:'regular',forms:["travel","traveled","traveled"],irregularDecoys:["trevel","travelt","trovel"],spellingDecoys:["travelleded","traveld"]},
    {type:'regular',forms:["try","tried","tried"],irregularDecoys:["trew","trought","tren"],spellingDecoys:["tryed","trid"]},
    {type:'regular',forms:["use","used","used"],irregularDecoys:["ose","usen","ust"],spellingDecoys:["useed","usd"]},
    {type:'regular',forms:["visit","visited","visited"],irregularDecoys:["vasit","visen","vist"],spellingDecoys:["visitted","visitd"]},
    {type:'regular',forms:["walk","walked","walked"],irregularDecoys:["wolk","walkt","welken"],spellingDecoys:["walkd","walkked"]},
    {type:'regular',forms:["wash","washed","washed"],irregularDecoys:["wish","washt","woshen"],spellingDecoys:["washd","washhed"]},
    {type:'regular',forms:["watch","watched","watched"],irregularDecoys:["wetch","wachten","wought"],spellingDecoys:["watchd","watchhed"]},
    {type:'regular',forms:["work","worked","worked"],irregularDecoys:["wark","workt","wurken"],spellingDecoys:["workd","workked"]},
  ];
  function findVerb(base){
    const key=String(base||'').toLowerCase();
    return VERBS.find(v=>v.forms[0]===key)||null;
  }
  const api={VERBS,findVerb};
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  global.VerbRunnerBank=api;
})(typeof window!=='undefined'?window:globalThis);
