function prompt(id, role, text) {
  return Object.freeze({ id, role, text, audioAsset: id.toLowerCase().replaceAll("_", "-") + ".wav" });
}
export const PROMPTS = Object.freeze({
  AED_STARTUP: prompt("AED_STARTUP","aed","Mantenga la calma. Siga estas instrucciones."),
  AED_CALL_HELP: prompt("AED_CALL_HELP","aed","Solicite ayuda médica de emergencia."),
  AED_EXPOSE_CHEST: prompt("AED_EXPOSE_CHEST","aed","Descubra el pecho del paciente."),
  AED_ATTACH_PADS: prompt("AED_ATTACH_PADS","aed","Coloque los electrodos como se muestra."),
  AED_CHECK_PADS: prompt("AED_CHECK_PADS","aed","Revise los electrodos."),
  AED_ANALYZING: prompt("AED_ANALYZING","aed","No toque al paciente. Analizando ritmo cardíaco."),
  AED_SHOCK_ADVISED: prompt("AED_SHOCK_ADVISED","aed","Se recomienda una descarga. No toque al paciente."),
  AED_PRESS_SHOCK: prompt("AED_PRESS_SHOCK","aed","Presione el botón de descarga."),
  AED_SHOCK_DELIVERED: prompt("AED_SHOCK_DELIVERED","aed","Descarga aplicada."),
  AED_NO_SHOCK: prompt("AED_NO_SHOCK","aed","No se recomienda una descarga."),
  AED_BEGIN_CPR: prompt("AED_BEGIN_CPR","aed","Inicie RCP."),
  AED_CONTINUE_CPR: prompt("AED_CONTINUE_CPR","aed","Continúe RCP."),
  AED_REASSESS: prompt("AED_REASSESS","aed","Prepárese para un nuevo análisis."),

  PARAMEDIC_CONTEXT_WET_CHEST: prompt("PARAMEDIC_CONTEXT_WET_CHEST","paramedic","Compañero, acabamos de sacar al paciente del agua. Tiene el tórax mojado."),
  PARAMEDIC_HINT_WET_CHEST: prompt("PARAMEDIC_HINT_WET_CHEST","paramedic","Compañero, revisa si las condiciones permiten colocar correctamente los electrodos."),
  PARAMEDIC_CONTEXT_MEDICATION_PATCH: prompt("PARAMEDIC_CONTEXT_MEDICATION_PATCH","paramedic","Compañero, veo un parche adherido justo donde iría uno de los electrodos."),
  PARAMEDIC_HINT_MEDICATION_PATCH: prompt("PARAMEDIC_HINT_MEDICATION_PATCH","paramedic","Compañero, revisa qué hay sobre la piel antes de colocar ese electrodo."),
  PARAMEDIC_CONTEXT_IMPLANTED_DEVICE: prompt("PARAMEDIC_CONTEXT_IMPLANTED_DEVICE","paramedic","Compañero, noto un dispositivo implantado debajo de la piel del pecho."),
  PARAMEDIC_HINT_IMPLANTED_DEVICE: prompt("PARAMEDIC_HINT_IMPLANTED_DEVICE","paramedic","Compañero, observa con cuidado la zona antes de decidir dónde colocar el electrodo."),
  PARAMEDIC_CONTEXT_CHEST_HAIR: prompt("PARAMEDIC_CONTEXT_CHEST_HAIR","paramedic","Compañero, el vello del tórax está impidiendo que el electrodo se adhiera bien."),
  PARAMEDIC_HINT_CHEST_HAIR: prompt("PARAMEDIC_HINT_CHEST_HAIR","paramedic","Compañero, revisa por qué el electrodo no está haciendo buen contacto."),
  PARAMEDIC_CONTEXT_PEDIATRIC: prompt("PARAMEDIC_CONTEXT_PEDIATRIC","paramedic","Compañero, nuestro paciente es un niño."),
  PARAMEDIC_HINT_PEDIATRIC: prompt("PARAMEDIC_HINT_PEDIATRIC","paramedic","Compañero, confirma que el equipo y la colocación sean apropiados para el tamaño del paciente."),
  PARAMEDIC_CONTEXT_PERSON_TOUCHING: prompt("PARAMEDIC_CONTEXT_PERSON_TOUCHING","paramedic","Compañero, hay una persona tocando al paciente."),
  PARAMEDIC_HINT_PERSON_TOUCHING: prompt("PARAMEDIC_HINT_PERSON_TOUCHING","paramedic","Compañero, mira quién está en contacto con el paciente antes de continuar."),
  PARAMEDIC_CONTEXT_MOVEMENT: prompt("PARAMEDIC_CONTEXT_MOVEMENT","paramedic","Compañero, están moviendo al paciente durante el análisis."),
  PARAMEDIC_HINT_MOVEMENT: prompt("PARAMEDIC_HINT_MOVEMENT","paramedic","Compañero, piensa qué puede alterar un análisis confiable del ritmo."),
  PARAMEDIC_CONTEXT_ELECTRICAL_HAZARD: prompt("PARAMEDIC_CONTEXT_ELECTRICAL_HAZARD","paramedic","Compañero, la fuente eléctrica de la escena sigue energizada."),
  PARAMEDIC_HINT_ELECTRICAL_HAZARD: prompt("PARAMEDIC_HINT_ELECTRICAL_HAZARD","paramedic","Compañero, revisa primero si la escena es segura para acercarnos."),

  PARAMEDIC_CONTEXT_PREGNANCY: prompt("PARAMEDIC_CONTEXT_PREGNANCY","paramedic","Compañero, observo que la paciente parece estar embarazada."),
  PARAMEDIC_HINT_PREGNANCY: prompt("PARAMEDIC_HINT_PREGNANCY","paramedic","Compañero, considera esta condición mientras continúas el algoritmo de reanimación."),
  PARAMEDIC_CONTEXT_OPIOID_ARREST: prompt("PARAMEDIC_CONTEXT_OPIOID_ARREST","paramedic","Compañero, encontramos indicios de consumo de opioides junto al paciente y no presenta signos de circulación."),
  PARAMEDIC_HINT_OPIOID_ARREST: prompt("PARAMEDIC_HINT_OPIOID_ARREST","paramedic","Compañero, no pierdas de vista qué intervención tiene prioridad cuando ya hay paro."),
  PARAMEDIC_CONTEXT_OPIOID_PULSE: prompt("PARAMEDIC_CONTEXT_OPIOID_PULSE","paramedic","Compañero, respira de forma muy lenta, pero todavía tiene pulso."),
  PARAMEDIC_HINT_OPIOID_PULSE: prompt("PARAMEDIC_HINT_OPIOID_PULSE","paramedic","Compañero, confirma si realmente estamos ante un paro antes de tratarlo como uno."),
  PARAMEDIC_CONTEXT_DROWNING: prompt("PARAMEDIC_CONTEXT_DROWNING","paramedic","Compañero, el colapso ocurrió después de un episodio de ahogamiento."),
  PARAMEDIC_HINT_DROWNING: prompt("PARAMEDIC_HINT_DROWNING","paramedic","Compañero, recuerda que en este mecanismo la falta de oxígeno es una parte central del problema."),
  PARAMEDIC_CONTEXT_HYPOTHERMIA: prompt("PARAMEDIC_CONTEXT_HYPOTHERMIA","paramedic","Compañero, estuvo expuesto al frío durante mucho tiempo y está muy frío al tacto."),
  PARAMEDIC_HINT_HYPOTHERMIA: prompt("PARAMEDIC_HINT_HYPOTHERMIA","paramedic","Compañero, ten presente que el frío intenso puede hacer muy difíciles de valorar los signos de vida."),
  PARAMEDIC_CONTEXT_HYPERTHERMIA: prompt("PARAMEDIC_CONTEXT_HYPERTHERMIA","paramedic","Compañero, estuvo expuesto a calor extremo antes del colapso."),
  PARAMEDIC_HINT_HYPERTHERMIA: prompt("PARAMEDIC_HINT_HYPERTHERMIA","paramedic","Compañero, además del paro, busca la causa reversible que nos está mostrando la escena."),
  PARAMEDIC_CONTEXT_ELECTROCUTION: prompt("PARAMEDIC_CONTEXT_ELECTROCUTION","paramedic","Compañero, el colapso ocurrió tras una descarga eléctrica."),
  PARAMEDIC_HINT_ELECTROCUTION: prompt("PARAMEDIC_HINT_ELECTROCUTION","paramedic","Compañero, antes de tocar al paciente confirma que el peligro eléctrico ya fue eliminado."),
  PARAMEDIC_CONTEXT_ANAPHYLAXIS: prompt("PARAMEDIC_CONTEXT_ANAPHYLAXIS","paramedic","Compañero, antes del colapso presentó una reacción alérgica grave y dificultad para respirar."),
  PARAMEDIC_HINT_ANAPHYLAXIS: prompt("PARAMEDIC_HINT_ANAPHYLAXIS","paramedic","Compañero, relaciona los hallazgos previos con una posible causa reversible del paro."),
  PARAMEDIC_CONTEXT_ASTHMA: prompt("PARAMEDIC_CONTEXT_ASTHMA","paramedic","Compañero, tenía una crisis asmática intensa antes de deteriorarse."),
  PARAMEDIC_HINT_ASTHMA: prompt("PARAMEDIC_HINT_ASTHMA","paramedic","Compañero, piensa qué problema respiratorio pudo llevar a este deterioro."),
  PARAMEDIC_CONTEXT_POISONING: prompt("PARAMEDIC_CONTEXT_POISONING","paramedic","Compañero, hay evidencia de una posible exposición a una sustancia tóxica."),
  PARAMEDIC_HINT_POISONING: prompt("PARAMEDIC_HINT_POISONING","paramedic","Compañero, usa las pistas de la escena para buscar una causa tratable además del algoritmo del paro."),
  PARAMEDIC_CONTEXT_PE: prompt("PARAMEDIC_CONTEXT_PE","paramedic","Compañero, el cuadro previo hace sospechar un evento tromboembólico."),
  PARAMEDIC_HINT_PE: prompt("PARAMEDIC_HINT_PE","paramedic","Compañero, considera si una causa obstructiva puede explicar el deterioro."),
  PARAMEDIC_CONTEXT_LVAD: prompt("PARAMEDIC_CONTEXT_LVAD","paramedic","Compañero, el paciente tiene un dispositivo de asistencia ventricular implantado."),
  PARAMEDIC_HINT_LVAD: prompt("PARAMEDIC_HINT_LVAD","paramedic","Compañero, no te bases en un solo signo para decidir si hay circulación."),
  PARAMEDIC_CONTEXT_ELECTROLYTES: prompt("PARAMEDIC_CONTEXT_ELECTROLYTES","paramedic","Compañero, el paciente tiene antecedentes que hacen pensar en una alteración grave de electrolitos."),
  PARAMEDIC_HINT_ELECTROLYTES: prompt("PARAMEDIC_HINT_ELECTROLYTES","paramedic","Compañero, busca una causa reversible relacionada con sus antecedentes."),
  PARAMEDIC_CONTEXT_AIRWAY_OBSTRUCTION: prompt("PARAMEDIC_CONTEXT_AIRWAY_OBSTRUCTION","paramedic","Compañero, el paciente se estaba atragantando antes de perder la respuesta."),
  PARAMEDIC_HINT_AIRWAY_OBSTRUCTION: prompt("PARAMEDIC_HINT_AIRWAY_OBSTRUCTION","paramedic","Compañero, reconstruye qué ocurrió antes del paro y qué problema pudo iniciarlo."),
  PARAMEDIC_CONTEXT_ROSC_SIGNS: prompt("PARAMEDIC_CONTEXT_ROSC_SIGNS","paramedic","Compañero, noto que el paciente empieza a moverse y aparecen signos de vida."),
  PARAMEDIC_HINT_ROSC_SIGNS: prompt("PARAMEDIC_HINT_ROSC_SIGNS","paramedic","Compañero, reevalúa al paciente antes de seguir actuando de forma automática."),
  PARAMEDIC_CONTEXT_REARREST: prompt("PARAMEDIC_CONTEXT_REARREST","paramedic","Compañero, el paciente que había recuperado signos de vida vuelve a quedar sin respuesta."),
  PARAMEDIC_HINT_REARREST: prompt("PARAMEDIC_HINT_REARREST","paramedic","Compañero, vuelve a valorar desde el principio qué estado tiene ahora.")
});
