const V=Math.max(1,Math.min(4,Number(window.STUDY_VERSION||1)))-1;
const svg=(title,sub,icon='⚙')=>'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500"><rect width="800" height="500" rx="28" fill="#f6f9fc"/><rect x="70" y="70" width="660" height="360" rx="28" fill="#fff" stroke="#d7e2ee" stroke-width="4"/><text x="400" y="205" text-anchor="middle" font-family="Arial" font-size="86" fill="#397df1">${icon}</text><text x="400" y="292" text-anchor="middle" font-family="Arial" font-weight="700" font-size="34" fill="#17335f">${title}</text><text x="400" y="340" text-anchor="middle" font-family="Arial" font-size="23" fill="#627694">${sub}</text></svg>`);
const mc=(kind,title,sub,icon,q,options,correct,why,hint)=>({type:'mcq',kind,img:svg(title,sub,icon),caption:sub,q,options,correct,why,hint});
const op=(kind,title,sub,icon,q,model,criteria,hint)=>({type:'open',kind,img:svg(title,sub,icon),caption:sub,q,model,criteria,hint});
const pick=a=>a[V];
const banks=[[],[],[],[]];
const add=(...qs)=>qs.forEach((q,i)=>banks[i].push(q));

add(
mc('Señales','Vibración muestreada','Lectura cada 2 s','●','Un sensor registra vibración únicamente cada 2 segundos. ¿Cómo se clasifica la señal registrada?',['Continua','Discreta','Estacionaria','MIMO'],1,['Continua tendría valor para todo instante.','Correcto: existe en instantes separados.','Estacionaria no describe muestreo.','MIMO clasifica entradas y salidas.'],'Observa cuándo existen los datos.'),
mc('Señales','Contador de piezas','Un pulso por producto','▮','Un contador entrega un valor cada vez que pasa una pieza. ¿Qué tipo de señal representa ese registro?',['Discreta','Continua','Lineal','Acoplada'],0,['Correcto: son eventos separados.','Continua implicaría definición en cualquier instante.','Linealidad es otra propiedad.','Acoplamiento no clasifica señales.'],'Piensa en eventos separados.'),
mc('Señales','Temperatura digital','Muestra cada 500 ms','◆','La temperatura física cambia continuamente, pero el controlador guarda una lectura cada 500 ms. La señal almacenada es…',['Continua','Discreta','Estática','No estacionaria necesariamente'],1,['La variable física puede ser continua, pero no el registro.','Correcto: el registro es discreto en el tiempo.','Estática se refiere a memoria.','No puede afirmarse solo por muestrear.'],'Distingue variable física de registro.'),
mc('Señales','Encoder incremental','Conteos de giro','↻','Un encoder genera conteos individuales conforme gira un eje. ¿Cómo se clasifica la señal de conteo?',['Discreta','Continua','Estacionaria','Planta'],0,['Correcto: se expresa mediante eventos separados.','No está definida continuamente.','Estacionaria es otra clasificación.','Planta no es un tipo de señal.'],'Conteos individuales = señal discreta.')
);

add(
mc('Variable manipulada','Horno eléctrico','Potencia aplicada','♨','El controlador cambia la potencia eléctrica para regular la temperatura. ¿Cuál es la variable manipulada?',['Temperatura','Potencia eléctrica','Set-point','Temperatura ambiente'],1,['Es la variable controlada.','Correcto: es la acción modificada.','Es la referencia.','Puede ser perturbación.'],'¿Qué cambia directamente el controlador?'),
mc('Variable manipulada','Tanque de nivel','Apertura de válvula','▤','Para mantener el nivel, el controlador cambia la apertura de una válvula. ¿Qué variable es manipulada?',['Nivel','Apertura de válvula','Caudal medido','Nivel deseado'],1,['Es la variable controlada.','Correcto: es la acción modificada.','Es una medición.','Es la referencia.'],'Busca la acción aplicada.'),
mc('Variable manipulada','Motor DC','Voltaje de armadura','⚡','Un controlador modifica el voltaje aplicado a un motor para regular velocidad. ¿Cuál es la variable manipulada?',['Velocidad','Voltaje aplicado','Velocidad deseada','Carga externa'],1,['Es la salida controlada.','Correcto: el voltaje es la acción.','Es el set-point.','Es una perturbación.'],'La manipulada provoca el efecto.'),
mc('Variable manipulada','Regulación de presión','Posición de válvula','◉','Un regulador ajusta una válvula para mantener presión constante. La variable manipulada es…',['Presión medida','Posición de válvula','Presión deseada','Fuga externa'],1,['Es la controlada.','Correcto: es la acción ajustada.','Es la referencia.','Es perturbación.'],'Identifica lo que el controlador ordena cambiar.')
);

add(
op('MISO','Mezclador químico','3 sensores → 1 válvula','⇢','Da un ejemplo de sistema MISO y argumenta por qué lo es.','Ejemplo: temperatura, pH y conductividad entran al controlador y éste genera una sola señal a una válvula dosificadora. Es MISO porque tiene múltiples entradas y una salida.',['Más de una entrada.','Una sola salida.','Argumentar contando entradas y salida.'],'MISO = varias entradas, una salida.'),
op('MISO','Ventilación','CO₂ + T + humedad → ventilador','⇢','Propón un sistema MISO aplicado a ventilación y justifica su clasificación.','El controlador recibe CO₂, temperatura y humedad y genera una sola señal de velocidad para un ventilador. Varias entradas y una salida: MISO.',['Identificar varias entradas.','Identificar una salida.','Explicar la clasificación.'],'No confundas sensores con salidas.'),
op('MISO','Riego inteligente','Humedad + luz + T → válvula','⇢','Da un ejemplo MISO de agricultura o riego y argumenta.','Humedad de suelo, temperatura y radiación entran al controlador y éste genera una única orden para una electroválvula.',['Varias entradas.','Una salida.','Argumentación explícita.'],'Cuenta señales de entrada y salida.'),
op('MISO','Gestión de batería','V + I + T → límite de carga','⇢','Construye un ejemplo de sistema MISO relacionado con una batería y explica la clasificación.','Voltaje, corriente y temperatura son entradas y la única salida es una señal para limitar la carga. Por eso es MISO.',['Más de una entrada.','Una salida.','Justificación por número de señales.'],'MISO no significa muchos actuadores.')
);

add(
mc('Planta / proceso / sistema','Elevador','Equipo físico','▤','Si se considera el elevador como el conjunto físico sobre el que actúa el controlador, corresponde principalmente a…',['Proceso','Planta','Set-point','Perturbación'],1,['Proceso sería el movimiento.','Correcto: se enfatiza el equipo físico.','Es valor deseado.','Es influencia externa.'],'Equipo físico = planta.'),
mc('Planta / proceso / sistema','Lavadora','Llenar → lavar → enjuagar','◌','Si interesa la secuencia de llenar, agitar, enjuagar y centrifugar, se está describiendo un…',['Sistema','Proceso','Planta','Sensor'],1,['Sistema es el conjunto.','Correcto: es una sucesión de operaciones.','Planta sería el equipo.','Sensor es un componente.'],'¿Objeto o secuencia?'),
mc('Planta / proceso / sistema','Dron','Componentes coordinados','✣','Motores, sensores, batería y controlador trabajando juntos para mantener vuelo forman un…',['Proceso','Sistema','Planta solamente','Set-point'],1,['Proceso sería la operación.','Correcto: componentes cooperando por un objetivo.','Aquí se enfatiza el conjunto completo.','Set-point es referencia.'],'Conjunto coordinado + objetivo.'),
mc('Planta / proceso / sistema','Reactor','Recipiente y tuberías','▥','El recipiente, agitador y tuberías de un reactor, considerados como objeto físico donde ocurre la operación, son la…',['Planta','Proceso','Salida','Referencia'],0,['Correcto: equipo físico.','Proceso sería la transformación.','Salida es resultado.','Referencia es valor deseado.'],'Se pregunta por el objeto físico.')
);

add(
mc('Sistema manual','Prensa mecánica','Palanca accionada por persona','☝','Una prensa solo se mueve cuando el operador acciona directamente una palanca. ¿Qué tipo de sistema es?',['Automático','Manual','Continuo','MIMO'],1,['Automático no exige esa intervención directa.','Correcto: la persona ejecuta la acción.','Es otra clasificación.','Clasifica entradas/salidas.'],'¿Quién ejecuta la acción?'),
mc('Sistema manual','Riego con llave','Apertura por trabajador','☝','Un trabajador abre y cierra una llave observando el cultivo. El sistema es…',['Manual','Automático','Discreto','Acoplado'],0,['Correcto: la acción depende de la persona.','No hay ejecución automática.','Es otra clasificación.','Es otra propiedad.'],'La persona decide y actúa.'),
mc('Sistema manual','Torno convencional','Avance con manivelas','☝','En un torno convencional el operador mueve las manivelas para posicionar la herramienta. ¿Cómo se clasifica respecto a intervención humana?',['Manual','Automático','Estacionario','Lazo cerrado necesariamente'],0,['Correcto: depende del operador.','No ejecuta por sí solo.','Otra propiedad.','Manual no define el tipo de lazo.'],'No confundas manual con lazo abierto.'),
mc('Sistema manual','Compuerta','Volante manual','☝','Una compuerta se abre girando un volante a mano y no tiene actuador automático. Es un sistema…',['Manual','Automático','MISO','Continuo'],0,['Correcto: la persona realiza la acción.','No hay actuador automático.','Otra clasificación.','Otra clasificación.'],'Acción humana directa.')
);

add(
mc('Lazo cerrado','Motor','Sensor de rpm','↩','Para que el controlador corrija la velocidad real de un motor, ¿qué información debe regresar al controlador?',['Medición de rpm','Solo referencia','Potencia nominal','Nombre del motor'],0,['Correcto: permite comparar y corregir.','No informa el resultado.','No sustituye realimentación.','No interviene.'],'La corrección exige conocer la salida.'),
mc('Lazo cerrado','Tanque','Transmisor de nivel','↩','Un actuador debe corregir el nivel de un tanque. ¿Qué necesita la lógica de lazo cerrado?',['Nivel medido realimentado','Otro tanque','Solo temporizador','Alarma independiente'],0,['Correcto: la salida vuelve al controlador.','No es requisito.','No informa nivel real.','Puede alertar, pero no cerrar el lazo.'],'Salida medida → controlador.'),
mc('Lazo cerrado','Servomotor','Encoder de posición','↩','Un servomotor debe corregir su posición. ¿Qué información hace posible esa corrección?',['Posición medida','Solo orden inicial','Tiempo transcurrido','Color del actuador'],0,['Correcto: permite calcular error.','No indica el resultado actual.','No sustituye medición.','No es variable funcional.'],'Debe medirse el resultado.'),
mc('Lazo cerrado','Tubería','Presión real','↩','Para corregir una desviación de presión, el controlador necesita…',['Presión real medida','Solo presión deseada','Diámetro de tubería','Tiempo de operación'],0,['Correcto: proporciona la salida actual.','No permite conocer el error por sí sola.','No sustituye medición.','No basta para corregir.'],'Sin salida medida no hay corrección por error.')
);

add(
mc('Sistema','Transportador','Banda + motor + sensores','⚙','Banda, motor, sensores y controlador trabajando juntos para mover cajas constituyen un…',['Proceso','Sistema','Perturbación','Set-point'],1,['Proceso sería la operación.','Correcto: componentes cooperan por un objetivo.','No es influencia externa.','No es referencia.'],'Componentes + objetivo.'),
mc('Sistema','Bomba solar','Panel + batería + bomba','⚙','Panel, batería, convertidor y bomba trabajando juntos para suministrar agua forman un…',['Sistema','Proceso','Planta únicamente','Variable'],0,['Correcto: conjunto cooperante.','Proceso sería el bombeo.','Aquí se enfatiza el conjunto completo.','Variable es una magnitud.'],'Piensa en el conjunto.'),
mc('Sistema','Puerta automática','Sensor + control + motor','⚙','Sensor, controlador y motor que cooperan para abrir una puerta forman un…',['Sistema','Proceso','Señal','Perturbación'],0,['Correcto: conjunto organizado.','Proceso sería la apertura.','Señal es información.','Perturbación es externa.'],'Conjunto organizado para una función.'),
mc('Sistema','Refrigeración','Compresor + evaporador + control','⚙','Los componentes de un equipo de refrigeración que interactúan para mantener frío un recinto forman un…',['Proceso','Sistema','Referencia','Salida'],1,['Proceso sería el ciclo.','Correcto: componentes y objetivo.','Es valor deseado.','Es resultado.'],'Varios elementos, una función común.')
);

const base8=['Variable a controlar, actuador y set-point','Planta, proceso y sensor','Entrada, salida y perturbación','Sensor, pantalla y operador'];
const why8=['Correcto: identifica qué se regula, quién actúa y la referencia.','No es la terna solicitada.','No incluye el elemento de actuación como se pide.','Una pantalla no es elemento base.'];
add(
mc('Lógica de control','Temperatura','Variable + actuador + referencia','△','Para construir la lógica básica de regulación de temperatura, ¿qué terna necesitas identificar?',base8,0,why8,'Qué controlas, quién actúa y a qué valor quieres llegar.'),
mc('Lógica de control','Nivel','Objetivo de regulación','△','¿Qué tres elementos base debe reconocer la lógica de un control de nivel?',base8,0,why8,'Busca variable, actuación y referencia.'),
mc('Lógica de control','Velocidad','Regulación de motor','△','En un control de velocidad, ¿qué conjunto resume los tres elementos base de la lógica?',base8,0,why8,'No confundas componentes físicos con lógica mínima.'),
mc('Lógica de control','Presión','Regulación de tubería','△','¿Qué combinación representa la base lógica para regular presión?',base8,0,why8,'Variable a controlar + actuador + set-point.')
);

add(
mc('Conceptos','Calefacción','Potencia vs temperatura','≠','En un calentador, la potencia aplicada y la temperatura obtenida ¿son la misma variable?',['Sí, ambas son salida','No; potencia puede ser manipulada y temperatura salida','Solo si es SISO','Solo en lazo abierto'],1,['Confunde acción con resultado.','Correcto: tienen funciones distintas.','SISO no las vuelve equivalentes.','El tipo de lazo tampoco.'],'Acción ≠ resultado.'),
mc('Conceptos','Tanque','Válvula vs nivel','≠','¿La apertura de la válvula puede llamarse simplemente “salida del sistema” cuando se usa para controlar nivel?',['Sí','No; es variable manipulada','Solo en MIMO','Solo si hay sensor'],1,['Confunde acción con resultado.','Correcto: la apertura es acción de control.','MIMO no cambia la definición.','El sensor tampoco.'],'¿Qué se modifica y qué se obtiene?'),
mc('Conceptos','Motor','Voltaje vs velocidad','≠','El voltaje aplicado al motor es variable manipulada. ¿Eso significa que también es la salida controlada?',['Sí','No','Solo en continuo','Solo en manual'],1,['La salida sería velocidad.','Correcto: son roles diferentes.','El tiempo no cambia los roles.','Manual tampoco.'],'No confundas acción con salida.'),
mc('Conceptos','Caudal','Válvula vs caudal','≠','Una válvula se mueve para modificar caudal. ¿La posición de válvula y el caudal son la misma variable?',['Sí, siempre','No; una es manipulada y otra puede ser controlada','Solo en SISO','Solo si hay realimentación'],1,['Son magnitudes distintas.','Correcto: cumplen roles diferentes.','SISO no las vuelve idénticas.','La realimentación tampoco.'],'Distingue causa de control y resultado.')
);

add(
mc('Sistema físico','Bicicleta','Materia + energía mecánica','🚲','Una bicicleta formada por cuadro, ruedas y transmisión es un sistema…',['Abstracto','Físico','Estacionario necesariamente','Desacoplado'],1,['No es solo modelo conceptual.','Correcto: elementos materiales y energía.','No necesariamente.','No puede afirmarse.'],'Materia + energía.'),
mc('Sistema físico','Brazo robótico','Motores y eslabones','⌁','Un brazo robótico con motores, engranes y estructura se clasifica como sistema…',['Físico','Abstracto','Discreto necesariamente','Estacionario'],0,['Correcto: es material y energético.','No es puramente conceptual.','No necesariamente.','No necesariamente.'],'¿Existe físicamente?'),
mc('Sistema físico','Circuito real','R + C + fuente','⌁','Un circuito real con resistencias, capacitores y fuente es un sistema…',['Físico','Abstracto','Manual necesariamente','No estacionario necesariamente'],0,['Correcto: existe físicamente e intercambia energía.','El modelo matemático sería abstracto.','No necesariamente.','No necesariamente.'],'Objeto real con energía.'),
mc('Sistema físico','Red hidráulica','Bomba + válvulas + tuberías','⌁','Una red hidráulica real se clasifica como sistema…',['Abstracto','Físico','Lineal necesariamente','SISO necesariamente'],1,['No es solo representación conceptual.','Correcto: materia y energía.','Puede ser o no lineal.','Puede tener varias entradas/salidas.'],'Se pregunta por naturaleza material.')
);

add(
mc('Entradas y salidas','Iluminación','1 sensor → 3 zonas','1→3','Un sensor de presencia activa tres zonas de iluminación consideradas como salidas independientes. ¿Qué clasificación corresponde?',['SISO','SIMO','MISO','MIMO'],1,['1 entrada y 1 salida.','Correcto: 1 entrada y varias salidas.','Varias entradas y 1 salida.','Varias de ambas.'],'Cuenta entradas y salidas.'),
mc('Entradas y salidas','Alarma','3 sensores → 1 alarma','3→1','Temperatura, humo y gas alimentan una sola señal de alarma. ¿Cómo se clasifica el bloque?',['SIMO','MISO','SISO','MIMO'],1,['1 entrada y varias salidas.','Correcto: varias entradas y una salida.','1 y 1.','Varias y varias.'],'Varias entran; una sale.'),
mc('Entradas y salidas','Robot móvil','2 referencias → 2 ruedas','2→2','Un robot recibe referencia lineal y angular y entrega velocidad de rueda izquierda y derecha. ¿Qué tipo es?',['SISO','SIMO','MISO','MIMO'],3,['No.','No: hay más de una entrada.','No: hay más de una salida.','Correcto: múltiples entradas y salidas.'],'2 entradas + 2 salidas.'),
mc('Entradas y salidas','Transmisor','1 presión → 1 señal','1→1','Un transmisor recibe presión y entrega una única señal eléctrica. ¿Cómo se clasifica?',['SISO','SIMO','MISO','MIMO'],0,['Correcto: una entrada y una salida.','Tendría varias salidas.','Tendría varias entradas.','Tendría varias de ambas.'],'Una entra, una sale.')
);

add(
mc('Lazo','Semáforo temporizado','Ciclo fijo sin medir tráfico','⏱','Un semáforo cambia por tiempos programados sin medir tráfico. ¿Qué tipo de lazo representa?',['Lazo cerrado','Lazo abierto','MIMO','Manual'],1,['Cerrado usaría medición para corregir.','Correcto: opera sin realimentación.','Otra clasificación.','No requiere acción humana continua.'],'Sin medición para corregir.'),
mc('Lazo','Termostato','Mide temperatura y corrige','↩','Un termostato mide temperatura y enciende o apaga calefacción según el error. ¿Qué lazo es?',['Lazo abierto','Lazo cerrado','Manual','SIMO'],1,['Sí usa medición.','Correcto: hay realimentación.','No depende de intervención continua.','Otra clasificación.'],'Mide salida y corrige.'),
mc('Lazo','Microondas','90 s sin medir alimento','⏱','Un microondas calienta durante 90 s sin medir la temperatura del alimento. ¿Cómo se clasifica?',['Lazo cerrado','Lazo abierto','Acoplado','MISO'],1,['No usa salida para corregir.','Correcto: acción por tiempo.','Otra propiedad.','Otra clasificación.'],'¿Mide el resultado?'),
mc('Lazo','Control crucero','Velocidad realimentada','↩','El control crucero mide velocidad y ajusta acelerador. ¿Qué tipo de lazo es?',['Lazo abierto','Lazo cerrado','Manual','Discreto necesariamente'],1,['Sí existe realimentación.','Correcto: velocidad medida corrige acción.','No depende de acción humana continua.','No necesariamente.'],'Salida medida usada para corregir.')
);

add(
mc('Tiempo continuo','Circuito RC','Ecuación diferencial','∫','Un circuito RC se modela con ecuación diferencial y t puede tomar cualquier valor real. El modelo es de tiempo…',['Discreto','Continuo','Manual','MISO'],1,['Discreto usa instantes separados.','Correcto: tiempo continuo.','Otra clasificación.','Otra clasificación.'],'Derivadas + cualquier instante.'),
mc('Tiempo continuo','Nivel','dh/dt','∫','El nivel h(t) se describe mediante dh/dt = qin − qout. ¿Cómo se clasifica temporalmente el modelo?',['Continuo','Discreto','Estático','Manual'],0,['Correcto: usa derivada respecto al tiempo.','Usaría diferencias/muestras.','No responde al dominio temporal.','Otra propiedad.'],'La derivada es la pista.'),
mc('Tiempo continuo','Motor DC','dω/dt','∫','La velocidad angular se modela mediante una ecuación diferencial. El sistema se considera de tiempo…',['Continuo','Discreto','Estacionario','Acoplado'],0,['Correcto: variable definida en tiempo continuo.','No corresponde.','Otra propiedad.','Otra propiedad.'],'Ecuación diferencial.'),
mc('Tiempo continuo','Modelo térmico','dT/dt','∫','Un modelo térmico usa dT/dt y supone que T existe para cualquier instante. ¿Qué tipo de tiempo utiliza?',['Discreto','Continuo','Manual','SISO'],1,['Usa instantes separados.','Correcto: cualquier t real.','Otra clasificación.','Clasifica entradas/salidas.'],'Cualquier t real.')
);

add(
op('Desacoplados','Dos ventiladores','Fuentes independientes','∥','Da un ejemplo de dos sistemas desacoplados y argumenta.','Dos ventiladores con fuentes independientes y sin señales compartidas. Cambiar uno no afecta variables del otro, por lo que están desacoplados.',['Dos sistemas identificables.','Sin influencia entre variables.','Explicar independencia.'],'Uno no altera al otro.'),
op('Desacoplados','Dos tanques aislados','Sin tubería común','∥','Propón un ejemplo de sistemas desacoplados usando dos depósitos y justifica.','Dos tanques con bombas y descargas independientes, sin conexión hidráulica. El nivel de uno no modifica al otro.',['Dos subsistemas.','Sin conexión que transmita influencia.','Argumentar con variables.'],'Cercanía física no implica acoplamiento.'),
op('Desacoplados','Dos motores','Controladores separados','∥','Da un ejemplo de sistemas desacoplados con motores eléctricos y argumenta.','Dos motores con fuentes y controladores independientes, sin carga mecánica común. La velocidad de uno no afecta la del otro.',['Dos motores.','Independencia de variables.','Justificación explícita.'],'Busca ausencia de influencia mutua.'),
op('Desacoplados','Dos cámaras','Climatización independiente','∥','Da un ejemplo de sistemas desacoplados en climatización y explica por qué.','Dos cámaras térmicamente aisladas con equipos independientes. La temperatura de una no afecta a la otra.',['Dos sistemas.','Sin transferencia relevante.','Explicar qué variables no se afectan.'],'No basta decir “están separados”.')
);

add(
mc('Proceso','Envasado','Llenar → tapar → etiquetar','→','Una operación formada por llenar, tapar, etiquetar y empacar en etapas sucesivas es un…',['Sistema','Proceso','Planta','Set-point'],1,['Sistema es el conjunto.','Correcto: secuencia progresiva.','Planta es el equipo.','Es referencia.'],'Secuencia de cambios.'),
mc('Proceso','Tratamiento de agua','Filtrar → sedimentar → desinfectar','→','Filtración, sedimentación y desinfección realizadas progresivamente describen un…',['Proceso','Planta','Sistema físico','Perturbación'],0,['Correcto: serie de operaciones sucesivas.','Es la instalación física.','Clasificación del conjunto.','Influencia externa.'],'Operaciones sucesivas.'),
mc('Proceso','Transformación térmica','Cambios graduales','→','La transformación gradual de una materia prima mediante varias etapas se denomina…',['Planta','Proceso','Sistema','Salida'],1,['Es equipo físico.','Correcto: cambios progresivos.','Es el conjunto.','Es resultado.'],'Algo que sucede progresivamente.'),
mc('Proceso','Carga de batería','Estado cambia por etapas','→','Una operación que cambia gradualmente el estado de carga hasta un valor final corresponde a un…',['Proceso','Planta','Sensor','Set-point'],0,['Correcto: evolución progresiva.','Es equipo físico.','Mide.','Es objetivo.'],'Cambios graduales = proceso.')
);

add(
mc('Planta / proceso / sistema','Refinería','Instalación industrial física','▥','La instalación industrial mostrada se considera principalmente ejemplo de…',['Proceso','Planta','Set-point','Señal'],1,['Proceso sería la transformación.','Correcto: se presenta la instalación física.','No es referencia.','No es señal.'],'Infraestructura física.'),
mc('Planta / proceso / sistema','Destilador','Equipo de laboratorio','⚗','Un montaje físico de destilación, sin describir aún las etapas, corresponde a…',['Planta','Proceso','Sistema abstracto','Salida'],0,['Correcto: equipo físico.','Sería la operación.','No es abstracto.','Sería producto obtenido.'],'Objeto físico antes que operación.'),
mc('Planta / proceso / sistema','Invernadero','Riego + ventilación + control','▦','Sensores, ventilación, riego y control trabajando juntos para cultivar forman un…',['Proceso','Sistema','Planta únicamente','Perturbación'],1,['Proceso sería una operación concreta.','Correcto: conjunto coordinado.','Aquí importa el conjunto funcional.','No es influencia externa.'],'Conjunto cooperante.'),
mc('Planta / proceso / sistema','Fábrica','Línea coordinada','▤','Una línea completa vista como componentes coordinados para producir piezas es un…',['Sistema','Proceso','Set-point','Perturbación'],0,['Correcto: conjunto y objetivo.','Proceso sería fabricación paso a paso.','No es referencia.','No es influencia externa.'],'Componentes + objetivo.')
);

add(
mc('Proceso','Fermentación','Transformación gradual','≈','La fermentación, como transformación que evoluciona gradualmente hasta un producto final, es un…',['Proceso','Planta','Sistema físico','Referencia'],0,['Correcto: evolución progresiva.','Sería el recipiente/equipo.','Clasificación del conjunto.','Es valor deseado.'],'Evolución gradual.'),
mc('Proceso','Secado','Pérdida gradual de humedad','≈','La reducción progresiva de humedad durante un secado se describe como un…',['Planta','Proceso','Salida','Sensor'],1,['Sería el secador.','Correcto: operación progresiva.','Es resultado.','Es componente.'],'Lo que cambia con el tiempo.'),
mc('Proceso','Pasteurización','Calentar → mantener → enfriar','≈','Calentar, mantener y enfriar de manera controlada constituye un…',['Proceso','Planta','Sistema abstracto','Perturbación'],0,['Correcto: etapas sucesivas.','Sería el equipo.','No es modelo abstracto.','No es perturbación.'],'Serie de etapas.'),
mc('Proceso','Horno','Calentamiento gradual','≈','El calentamiento gradual de una pieza hasta una temperatura objetivo se clasifica como…',['Sistema','Proceso','Planta','Set-point'],1,['Es el conjunto.','Correcto: operación progresiva.','Es equipo físico.','Es valor deseado.'],'Operación que evoluciona.')
);

add(
mc('Planta / proceso / sistema','Motocicleta','Vehículo completo','🏍','Una motocicleta completa, considerada como conjunto de componentes para transportarse, es un…',['Sistema','Proceso','Set-point','Señal'],0,['Correcto: conjunto con objetivo.','Proceso sería conducción/movimiento.','No es referencia.','No es señal.'],'Conjunto que cumple una función.'),
mc('Planta / proceso / sistema','Bomba centrífuga','Equipo físico','◉','Una bomba centrífuga considerada como equipo físico sobre el que se analiza control es una…',['Proceso','Planta','Sistema abstracto','Salida'],1,['Proceso sería bombeo.','Correcto: equipo físico.','No es modelo conceptual.','Podría ser caudal o presión.'],'Se pregunta por el equipo.'),
mc('Planta / proceso / sistema','Impresión 3D','Fabricación capa a capa','▧','La fabricación capa por capa de una pieza se considera un…',['Sistema','Proceso','Planta','Perturbación'],1,['Sistema sería impresora completa.','Correcto: operación progresiva.','Planta sería hardware.','No es perturbación.'],'La imagen enfatiza operación.'),
mc('Planta / proceso / sistema','Elevador','Cabina + motor + sensores','⇅','Cabina, motor, cables, sensores y control trabajando juntos para transportar personas forman un…',['Proceso','Sistema','Planta solamente','Referencia'],1,['Proceso sería viaje/movimiento.','Correcto: conjunto funcional.','Aquí se enfatiza cooperación.','Sería piso deseado.'],'Conjunto + objetivo.')
);

add(
op('Lazo abierto','Ejemplos domésticos','Sin realimentación','○','Da tres ejemplos domésticos de sistemas de lazo abierto y argumenta uno.','Tostador por tiempo, microondas por tiempo y ventilador con temporizador. Son abiertos si la salida no se mide para modificar automáticamente la acción.',['Tres ejemplos.','Al menos una justificación.','Mencionar ausencia de realimentación.'],'No basta decir “automático”.'),
op('Lazo abierto','Ejemplos industriales','Acción programada','○','Da tres ejemplos industriales de lazo abierto y argumenta uno.','Banda a velocidad fija sin sensor de salida, dosificador por tiempo y horno temporizado sin medición de producto.',['Tres casos.','Justificar uno.','Explicar que la salida no vuelve al controlador.'],'Busca controles por tiempo o ajuste fijo.'),
op('Lazo abierto','Ejemplos cotidianos','Salida no medida','○','Menciona tres sistemas cotidianos de lazo abierto y justifica al menos uno.','Licuadora por tiempo, lámpara con temporizador y aspersor programado sin sensor de humedad. La salida no se usa para corregir.',['Tres ejemplos.','Una explicación.','Ausencia de medición de salida.'],'Programado no significa cerrado.'),
op('Lazo abierto','Ejemplos de ingeniería','Sin corrección automática','○','Propón tres ejemplos de control en lazo abierto y argumenta uno con lenguaje de control.','Motor con voltaje fijo sin medir velocidad, calentador por tiempo y bomba durante tiempo fijo. La salida no se realimenta para corregir.',['Tres ejemplos.','Usar vocabulario de control.','Explicar no realimentación.'],'La salida no modifica la acción.')
);

add(
mc('Comportamiento temporal','Temperatura','Calentamiento por etapas','↗','Una curva de temperatura sube y cambia de nivel conforme avanza un calentamiento. Durante esa evolución el comportamiento es…',['Estacionario','No estacionario','Desacoplado','MISO'],1,['Implicaría permanencia.','Correcto: cambia con el tiempo.','No trata subsistemas.','No cuenta entradas/salidas.'],'¿Permanece constante?'),
mc('Comportamiento temporal','Nivel','Llenado de tanque','↗','El nivel aumenta durante el llenado antes de llegar a régimen. En ese intervalo el comportamiento es…',['Estacionario','No estacionario','Lineal necesariamente','SISO necesariamente'],1,['No permanece constante.','Correcto: evoluciona con el tiempo.','No puede concluirse.','No puede concluirse.'],'Transitorio = cambia con el tiempo.'),
mc('Comportamiento temporal','Velocidad','Arranque de motor','↗','La velocidad aumenta desde cero hasta su valor de operación. Durante el arranque es…',['No estacionario','Estacionario','Desacoplado','Manual'],0,['Correcto: cambia durante el arranque.','Aún no permanece constante.','Otra propiedad.','Otra clasificación.'],'Arranque ≠ régimen.'),
mc('Comportamiento temporal','Presión','Presurización','↗','Una presión sube gradualmente hasta estabilizarse. Mientras está subiendo, el comportamiento es…',['Estacionario','No estacionario','MIMO','Lazo abierto necesariamente'],1,['Sería cuando ya permanece constante.','Correcto: cambia con el tiempo.','No hay datos de I/O.','No hay datos de realimentación.'],'Fíjate solo en evolución temporal.')
);

add(
op('Estable y estacionario','Circuito RC','Régimen permanente','≈','Da un ejemplo de un sistema estable y estacionario y argumenta ambas propiedades.','Un circuito RC con entrada constante en régimen: estable porque entrada acotada produce salida acotada y estacionario porque sus variables permanecen constantes.',['Explicar estabilidad.','Explicar estacionariedad.','No basta nombrar sistema.'],'Son dos propiedades distintas.'),
op('Estable y estacionario','Tanque','Nivel en equilibrio','≈','Propón un sistema de nivel que sea estable y estacionario y justifica.','Un tanque en régimen con entrada y salida constantes y nivel fijo. Estable si perturbaciones acotadas producen respuestas acotadas y estacionario si el nivel permanece constante.',['Justificar estabilidad.','Justificar estacionariedad.','Distinguir ambas propiedades.'],'Estable no significa automáticamente estacionario.'),
op('Estable y estacionario','Horno','Temperatura en régimen','≈','Da un ejemplo térmico de sistema estable y estacionario y argumenta.','Un horno regulado que ya alcanzó temperatura constante: estable si no diverge ante perturbaciones acotadas y estacionario cuando sus variables se mantienen constantes.',['Dos justificaciones.','Idea de acotamiento.','Idea de constancia temporal.'],'Una propiedad habla de límites; otra de constancia.'),
op('Estable y estacionario','Motor','Velocidad de régimen','≈','Construye un ejemplo con un motor que sea estable y estacionario y argumenta.','Un motor a velocidad constante en régimen: estable si perturbaciones acotadas no hacen divergir velocidad y estacionario cuando las variables permanecen constantes.',['Explicar por qué no diverge.','Explicar por qué permanece constante.','Argumentar, no solo nombrar.'],'Régimen permanente ayuda con estacionariedad.')
);

add(
mc('Planta / proceso / sistema','Patín eléctrico','Batería + motor + control','🛴','Batería, controlador, motor, freno y estructura de un patín trabajando juntos forman un…',['Proceso','Sistema','Set-point','Perturbación'],1,['Proceso sería desplazamiento.','Correcto: conjunto con objetivo.','No es referencia.','No es influencia externa.'],'Conjunto funcional.'),
mc('Planta / proceso / sistema','Cafetera','Equipo físico','☕','Una cafetera considerada como equipo físico donde se calienta y hace pasar agua corresponde a la…',['Planta','Proceso','Salida','Perturbación'],0,['Correcto: equipo físico.','Proceso sería preparación del café.','Salida sería bebida.','No es influencia externa.'],'Objeto físico.'),
mc('Planta / proceso / sistema','Robot aspirador','Sensores + ruedas + control','◉','Sensores, ruedas, batería y control de un robot aspirador trabajando juntos constituyen un…',['Sistema','Proceso','Planta únicamente','Señal'],0,['Correcto: conjunto coordinado.','Proceso sería limpieza.','Aquí se enfatiza el conjunto completo.','No es una señal.'],'Componentes cooperando.'),
mc('Planta / proceso / sistema','Secadora','Pérdida de humedad','♨','La reducción gradual de humedad de la ropa dentro de una secadora corresponde a un…',['Planta','Proceso','Sistema físico','Set-point'],1,['Planta sería secadora física.','Correcto: transformación progresiva.','Clasifica el equipo.','Podría ser un valor deseado.'],'La pregunta habla de transformación.')
);

add(
mc('Estabilidad','Respuesta amortiguada','Oscilaciones decrecientes','〰','La salida oscila pero cada oscilación es menor y finalmente se aproxima a la referencia. ¿Qué propiedad se observa?',['Inestabilidad','Estabilidad','MISO','Desacoplamiento'],1,['Tendería a crecer o no permanecer acotada.','Correcto: permanece acotada y converge.','No cuenta I/O.','No compara subsistemas.'],'¿Diverge o converge?'),
mc('Estabilidad','Respuesta acotada','Perturbación limitada','〰','Una perturbación limitada produce una salida que cambia pero nunca crece sin límite. ¿Qué propiedad describe esto?',['Estabilidad','Estacionariedad','Aditividad','MIMO'],0,['Correcto: entrada acotada → salida acotada.','La salida puede variar y ser estable.','Es propiedad de linealidad.','Clasifica I/O.'],'Acotada → acotada.'),
mc('Estabilidad','Motor','Recuperación de velocidad','〰','Tras una perturbación, la velocidad se desvía y luego regresa sin crecer indefinidamente. El comportamiento es…',['Estable','Inestable','Desacoplado','Manual'],0,['Correcto: permanece limitada.','Implicaría divergencia.','Otra propiedad.','Otra clasificación.'],'La desviación no crece sin control.'),
mc('Estabilidad','Nivel','Oscilación amortiguada','〰','El nivel sobrepasa el valor deseado, oscila y termina acercándose a él. ¿Qué propiedad ilustra?',['Estacionariedad','Estabilidad','SIMO','Aditividad'],1,['Durante transitorio no es estacionario.','Correcto: respuesta acotada y convergente.','No cuenta salidas.','No suma entradas.'],'Sobrepaso no implica inestabilidad.')
);

add(
mc('Proceso','Decisión','Observar → evaluar → decidir → actuar','①','La secuencia observar, evaluar opciones, decidir y actuar representa principalmente un…',['Sistema','Proceso','Planta','Set-point'],1,['Sistema es el conjunto.','Correcto: secuencia progresiva.','Planta sería soporte físico.','Set-point es referencia.'],'Secuencia de pasos.'),
mc('Proceso','Mantenimiento','Detectar → diagnosticar → reparar','②','Detectar falla, diagnosticar, elegir solución y reparar describe un…',['Proceso','Planta','Sistema físico','Variable'],0,['Correcto: etapas sucesivas.','Planta sería equipo intervenido.','Clasifica el conjunto.','Variable es magnitud.'],'Etapas que llevan a un resultado.'),
mc('Proceso','Diseño','Definir → modelar → probar','③','Definir requisitos, modelar, prototipar y probar corresponde a un…',['Planta','Proceso','Set-point','Perturbación'],1,['Planta es objeto físico.','Correcto: secuencia progresiva.','Es valor deseado.','Es influencia externa.'],'Serie ordenada de acciones.'),
mc('Proceso','Calidad','Inspeccionar → comparar → decidir','④','Inspeccionar una pieza, comparar con tolerancia y decidir aceptación forma un…',['Sistema físico','Proceso','Planta','Señal'],1,['Puede ocurrir en un sistema físico, pero se pregunta por la secuencia.','Correcto: acciones sucesivas.','Planta sería equipo.','Señal es información.'],'Lo importante es la sucesión.')
);

add(
mc('Sistema de control','Climatización','Regula temperatura','◎','Un conjunto de componentes que regula temperatura para lograr un valor predeterminado es un…',['Proceso','Sistema de control','Planta','Perturbación'],1,['Proceso sería evolución térmica.','Correcto: regula para lograr funcionamiento deseado.','Planta sería equipo físico.','Es influencia externa.'],'La definición incluye regular.'),
mc('Sistema de control','Velocidad','Regula un motor','◎','Un conjunto que modifica su acción para mantener velocidad cerca de un valor deseado es un…',['Sistema de control','Proceso','Sistema físico solamente','Señal discreta'],0,['Correcto: su función es regular.','Proceso sería evolución.','El rasgo clave es regulación.','No se pregunta por señal.'],'Función principal: regular.'),
mc('Sistema de control','Nivel','Sensor + controlador + actuador','◎','Sensor, controlador y actuador coordinados para mantener nivel representan un…',['Planta','Sistema de control','Proceso','Set-point'],1,['Planta sería tanque/equipo.','Correcto: regulan la variable.','Proceso sería llenado/vaciado.','Es solo valor deseado.'],'Conjunto que regula.'),
mc('Sistema de control','Posición','Servosistema','◎','Un conjunto que ajusta un actuador para llevar una posición a un valor predeterminado se define como…',['Sistema de control','Proceso','Planta','Perturbación'],0,['Correcto: regula para alcanzar objetivo.','Proceso sería movimiento.','Planta sería mecanismo.','Perturbación sería externa.'],'Regulación hacia un objetivo.')
);

add(
mc('Sistema físico','Automóvil','Materia + energía','▣','Un automóvil real, compuesto por elementos materiales y energéticos que interactúan, es un sistema…',['Físico','Abstracto','Estacionario','Discreto'],0,['Correcto: definición de sistema físico.','Sería modelo conceptual.','Otra propiedad.','Otra clasificación.'],'Elementos materiales + energía.'),
mc('Sistema físico','Máquina CNC','Estructura + motores','▣','Una CNC real con estructura, motores y energía eléctrica se clasifica como sistema…',['Abstracto','Físico','MISO necesariamente','Estacionario'],1,['No es solo representación conceptual.','Correcto: elementos materiales y energéticos.','No necesariamente.','No necesariamente.'],'Existe materialmente.'),
mc('Sistema físico','Bomba hidráulica','Impulsor + flujo','▣','Una bomba hidráulica real con impulsor y flujo de energía se considera sistema…',['Físico','Abstracto','Lineal necesariamente','Continuo necesariamente'],0,['Correcto: conjunto material y energético.','Sería el modelo matemático.','No necesariamente.','No necesariamente.'],'Objeto real, no modelo.'),
mc('Sistema físico','Brazo mecánico','Eslabones + actuadores','▣','Un mecanismo con eslabones, actuadores y energía que interactúan para mover una carga es un sistema…',['Físico','Abstracto','Estacionario','SISO necesariamente'],0,['Correcto: componentes materiales y energía.','No es puramente conceptual.','No necesariamente.','Puede tener varias I/O.'],'Material + energía.')
);

add(
mc('Variable controlada','Tanque','Mantener nivel','▤','Una bomba y una válvula actúan para mantener la altura del líquido. ¿Cuál es la variable controlada?',['Apertura de válvula','Nivel del líquido','Velocidad de bomba','Tiempo'],1,['Puede ser manipulada.','Correcto: es la magnitud a regular.','Puede ser acción de control.','No es objetivo principal.'],'¿Qué magnitud quieres mantener?'),
mc('Variable controlada','Horno','Mantener 180 °C','♨','El controlador cambia potencia para mantener 180 °C. ¿Qué variable está controlando?',['Potencia','Temperatura','Corriente','Tiempo'],1,['Es manipulada.','Correcto: es la magnitud regulada.','Puede relacionarse con acción.','No es objetivo principal.'],'La controlada es el resultado a regular.'),
mc('Variable controlada','Motor','Mantener 1500 rpm','↻','Un variador cambia frecuencia para mantener 1500 rpm. ¿Cuál es la variable controlada?',['Frecuencia aplicada','Velocidad del motor','Voltaje nominal','Carga'],1,['Es manipulada.','Correcto: se regula velocidad.','Es parámetro.','Es perturbación.'],'Busca la magnitud objetivo.'),
mc('Variable controlada','Tubería','Mantener 3 bar','◉','Una válvula se ajusta para mantener 3 bar. ¿Cuál es la variable controlada?',['Apertura de válvula','Presión','Caudal de mando','Posición del actuador'],1,['Es acción de control.','Correcto: se regula presión.','No es objetivo.','Es variable manipulada/interna.'],'¿Qué valor se intenta mantener?')
);

add(
mc('Lazo','Grifo automático','Sensor detecta manos','✋','Un grifo detecta manos y abre el agua en respuesta a esa medición. Representa mejor un…',['Lazo abierto','Lazo cerrado','Sistema manual','MISO'],1,['Actúa con información del sensor.','Correcto: la medición modifica la acción.','No requiere accionar válvula manualmente.','Otra clasificación.'],'La medición cambia la acción.'),
mc('Lazo','Lámpara automática','Sensor de luz','☀','Una lámpara mide iluminación ambiental y ajusta su intensidad. ¿Qué tipo de lazo representa?',['Lazo abierto','Lazo cerrado','Manual','SIMO'],1,['Sí usa medición para ajustar.','Correcto: hay realimentación.','No depende de acción humana continua.','Otra clasificación.'],'Mide y corrige.'),
mc('Lazo','Bomba con flotador','Nivel detectado','↕','Una bomba se enciende o apaga según un flotador que detecta nivel. ¿Qué tipo de lazo es?',['Lazo cerrado','Lazo abierto','Manual','MIMO necesariamente'],0,['Correcto: la medición determina la acción.','No sería abierto porque usa nivel.','No depende del operador.','No puede afirmarse MIMO.'],'El sensor decide la acción según salida.'),
mc('Lazo','Calefactor','Termostato mide temperatura','♨','Un calefactor mide temperatura y se apaga al alcanzar el valor deseado. ¿Qué lazo representa?',['Lazo abierto','Lazo cerrado','Manual','Discreto necesariamente'],1,['Sí usa salida medida.','Correcto: temperatura real modifica la acción.','No necesita ajuste humano continuo.','No necesariamente.'],'La salida medida altera la acción.')
);

add(
mc('Aditividad','Superposición','Suma de entradas','+','Si la respuesta a x₁+x₂ es igual a y₁+y₂, ¿qué propiedad se cumple?',['Proporcionalidad','Aditividad','Estabilidad','Estacionariedad'],1,['Trata escalamiento.','Correcto: respuesta a suma = suma de respuestas.','Trata acotamiento.','Trata constancia.'],'La operación clave es sumar.'),
mc('Aditividad','Sistema lineal','Respuestas separadas','+','Un sistema responde y₁ a u₁ y y₂ a u₂. Si ante u₁+u₂ responde y₁+y₂, se verifica…',['Aditividad','Proporcionalidad','Acoplamiento','Estabilidad'],0,['Correcto: esa es aditividad.','Usa multiplicación por constante.','Otra propiedad.','Otra propiedad.'],'Suma de entradas → suma de salidas.'),
mc('Aditividad','Operador T','T[x₁+x₂]','+','La igualdad T[x₁+x₂]=T[x₁]+T[x₂] corresponde a…',['Estabilidad','Aditividad','Estacionariedad','MISO'],1,['No habla de acotamiento.','Correcto: expresa aditividad.','No habla de constancia.','No clasifica I/O.'],'Mira la suma dentro y fuera de T.'),
mc('Aditividad','Suma de efectos','Dos entradas juntas','+','Si aplicar dos entradas juntas produce exactamente la suma de los efectos que tendrían por separado, el sistema cumple…',['Proporcionalidad','Aditividad','Lazo cerrado','Desacoplamiento'],1,['Trata escalamiento.','Correcto: los efectos se suman.','No define esta propiedad.','Trata independencia entre subsistemas.'],'Efectos por separado que se suman.')
);

window.QUESTION_BANK=banks[V];
if(window.QUESTION_BANK.length!==29) throw new Error('Cada versión debe contener exactamente 29 preguntas');