const V=Number(window.STUDY_VERSION||1)-1;
const rot=(a,n)=>a.map((_,i)=>a[(i+n)%a.length]);
const mc=(kind,img,caption,qs,options,correct,why,hint)=>({type:'mcq',kind,img,caption,q:qs[V],options:rot(options,V),correct:(correct-V+options.length)%options.length,why:rot(why,V),hint});
const op=(kind,img,caption,qs,model,criteria,hint)=>({type:'open',kind,img,caption,q:qs[V],model,criteria,hint});
window.QUESTION_BANK=[
mc('Señales','discrete-signal.svg','La señal aparece en instantes separados.',[
'¿La imagen muestra una señal de tipo?','¿Cómo se clasifica la señal representada por muestras aisladas?','Si x[n] solo existe en instantes numerados, ¿qué tipo de señal es?','En la gráfica no hay valor definido entre muestras. ¿Cuál es la clasificación correcta?'],['Continua','Discreta','Estacionaria','Lineal'],1,['Continua exige estar definida para cualquier instante.','Correcto: la señal está definida en instantes separados.','Estacionaria describe constancia, no muestreo.','La gráfica no demuestra linealidad.'],'Observa si hay valor para todo instante o solo para muestras.'),
mc('Variable manipulada','thermostat.jpg','El controlador modifica una acción para influir en la variable que desea regular.',[
'La cantidad o condición que el controlador modifica para afectar la variable controlada se conoce como…','¿Qué nombre recibe la variable que el controlador cambia directamente para provocar un efecto en la salida?','En un control de temperatura se ajusta la potencia del calentador. Esa potencia es la…','Si el controlador cambia una señal para influir en la variable regulada, esa señal corresponde a la…'],['Variable controlada','Variable manipulada','Referencia','Perturbación'],1,['Es la magnitud que se desea regular.','Correcto: es la acción que modifica el controlador.','Es el valor deseado.','Es una influencia externa no deseada.'],'Piensa en lo que cambia el controlador, no en lo que quiere mantener.'),
op('MISO','line.jpg','Debes justificar la clasificación contando entradas y salidas.',[
'Da un ejemplo de un sistema MISO y argumenta.','Propón un sistema con múltiples entradas y una sola salida y explica por qué es MISO.','Describe un caso real MISO indicando claramente cuáles son sus entradas y cuál es su salida.','Construye un ejemplo MISO y demuestra la clasificación contando variables.'],'Ejemplo: un controlador recibe temperatura, presión y caudal y genera una sola señal de apertura para una válvula. Es MISO porque tiene múltiples entradas y una sola salida.',['Más de una entrada.','Una sola salida.','La argumentación debe identificar ambas cantidades.'],'MISO = Multiple Input, Single Output.'),
mc('Planta / proceso / sistema','tank.jpg','El tanque se considera como equipo físico.',[
'Si se considera un tanque industrial como el equipo físico sobre el que se realiza una operación, corresponde a…','En un sistema de nivel, ¿qué término describe al tanque cuando interesa el equipo físico?','Tanque, tuberías y elementos físicos sobre los que actúa el control constituyen principalmente la…','Si el interés está en el objeto físico y no en la operación de llenado, ¿qué concepto corresponde?'],['Proceso','Sistema','Planta','Set-point'],2,['Proceso es lo que ocurre progresivamente.','Sistema enfatiza componentes que cooperan para un objetivo.','Correcto: planta es el equipo físico sobre el que se realiza la operación.','Set-point es un valor deseado.'],'Equipo físico = planta.'),
mc('Sistema manual','washer.jpg','La clasificación depende de la intervención humana.',[
'¿Cómo se clasifica un sistema que requiere a una persona para ejecutar la acción que le indica qué hacer?','Un operador debe accionar manualmente cada cambio importante del sistema. ¿Cómo se clasifica?','Si la ejecución de la acción depende directamente de una persona, el sistema es…','¿Qué tipo de sistema necesita intervención humana para indicar o efectuar la acción?'],['Automático','Manual','Acoplado','Continuo'],1,['Automático no exige la ejecución humana de cada acción.','Correcto: esa es la característica del sistema manual.','Acoplado describe relación entre variables.','Continuo describe el dominio temporal.'],'¿Quién ejecuta la acción?'),
mc('Lazo cerrado','thermostat.jpg','La corrección depende de conocer la salida real.',[
'¿Qué debe estar presente para que el actuador realice una corrección a la salida en un sistema de lazo cerrado?','Para corregir el error, ¿qué información necesita regresar al controlador?','¿Qué elemento lógico distingue al lazo cerrado cuando debe corregirse la salida?','El actuador solo puede corregir con base en el resultado si existe…'],['Realimentación de la salida','Solo un temporizador','Una segunda planta','Una entrada adicional cualquiera'],0,['Correcto: la salida medida se utiliza para corregir.','Un temporizador no informa el resultado real.','No es requisito para cerrar el lazo.','Una entrada adicional no sustituye la realimentación.'],'La salida debe volver al controlador.'),
mc('Sistema','line.jpg','Varios componentes cooperan para un objetivo.',[
'Una combinación de componentes que actúan juntos y realizan un objetivo determinado es un…','¿Qué concepto corresponde a elementos que interactúan para alcanzar un objetivo común?','Una línea de producción completa, vista como componentes que trabajan conjuntamente, es un…','Cuando interesa el conjunto organizado que realiza una función, hablamos de un…'],['Proceso','Sistema','Planta','Perturbación'],1,['Proceso es una secuencia de cambios.','Correcto: esa es la definición de sistema.','Planta es el equipo físico sobre el que ocurre la operación.','Perturbación es una influencia externa.'],'Conjunto + objetivo común.'),
mc('Lógica de control','thermostat.jpg','Se relacionan la variable a controlar, la acción y la referencia.',[
'¿Cuáles son los tres elementos base de la lógica de un sistema de control?','¿Qué terna describe mejor la lógica mínima de regulación?','Para regular una magnitud se necesita identificar la variable, actuar sobre el sistema y fijar un valor deseado. ¿Qué opción reúne esos elementos?','¿Cuál conjunto contiene variable a controlar, elemento de acción y referencia?'],['Variable a controlar, actuador y set-point','Planta, proceso y señal','Sensor, pantalla y operador','Entrada, salida y MIMO'],0,['Correcto: reúne la variable, la acción física y la referencia.','Son conceptos del curso, pero no la terna solicitada.','Una pantalla no es elemento base.','MIMO es una clasificación, no un elemento lógico.'],'Variable + actuador + referencia.'),
mc('Variable manipulada','sensor.jpg','Acción aplicada y salida resultante son conceptos distintos.',[
'¿La variable manipulada es conocida también como la salida del sistema?','¿Variable manipulada y salida significan lo mismo?','Si una señal es manipulada por el controlador, ¿puede llamarse automáticamente salida del sistema?','¿Qué afirmación es correcta sobre variable manipulada y salida?'],['Sí, siempre','No, son conceptos distintos','Solo en sistemas SISO','Solo en lazo abierto'],1,['No: la acción aplicada y el resultado no son lo mismo.','Correcto: variable manipulada es la acción; salida es el resultado.','SISO no vuelve equivalentes esos conceptos.','El tipo de lazo tampoco los vuelve equivalentes.'],'Acción ≠ resultado.'),
mc('Sistema físico','line.jpg','Se observan componentes materiales y energéticos.',[
'Un tren, una máquina o una línea de producción se clasifican como sistemas…','¿Qué tipo de sistema está compuesto por elementos materiales que intercambian energía?','Una máquina real con componentes físicos pertenece a la categoría de sistemas…','Si el sistema está constituido por materia y energía, se clasifica como…'],['Abstractos','Físicos','Estacionarios necesariamente','Desacoplados necesariamente'],1,['Abstracto no se define por componentes materiales.','Correcto: esa es la definición de sistema físico.','Ser físico no implica estacionariedad.','Ser físico tampoco implica desacoplamiento.'],'Material + energía.'),
mc('Entradas y salidas','simo.svg','Una sola entrada produce varias salidas.',[
'¿Cómo se clasifica el sistema mostrado según su número de entradas y salidas?','Una entrada alimenta el bloque y se observan cuatro salidas. ¿Qué clasificación corresponde?','¿Qué sigla representa una entrada y múltiples salidas?','El diagrama presenta Single Input y Multiple Output. ¿Cuál opción coincide?'],['SISO','SIMO','MISO','MIMO'],1,['Una entrada y una salida.','Correcto: Single Input, Multiple Output.','Múltiples entradas y una salida.','Múltiples entradas y múltiples salidas.'],'Cuenta flechas de entrada y salida.'),
mc('Lazo abierto','toaster.jpg','El tostador opera por tiempo sin medir el resultado para corregirse.',[
'¿Un tostador por tiempo representa lazo abierto o cerrado?','Un tostador termina el ciclo por temporizador y no mide el dorado. ¿Qué tipo de lazo es?','Si la salida “nivel de tostado” no regresa al control, ¿cómo se clasifica?','El tiempo determina la acción y el resultado no se usa para ajustar el ciclo. ¿Qué lazo es?'],['Lazo cerrado','Lazo abierto','MIMO','Acoplado'],1,['Lazo cerrado requiere realimentación.','Correcto: la salida no se utiliza para corregir.','MIMO es otra clasificación.','Acoplado describe relación entre variables.'],'Sin realimentación = lazo abierto.'),
mc('Tiempo continuo','tank.jpg','El proceso puede modelarse con una ecuación diferencial.',[
'Si el modelo está definido por una ecuación diferencial y el tiempo se considera infinitamente divisible, se trata de un sistema…','Un modelo con variables definidas para cualquier instante y ecuaciones diferenciales es de tiempo…','¿Qué clasificación temporal corresponde a un modelo donde t puede tomar cualquier valor real?','Si el tiempo no se restringe a instantes de muestreo y el modelo usa derivadas, el sistema es…'],['Discreto','Continuo','Manual','Estacionario'],1,['Discreto usa instantes separados.','Correcto: corresponde a tiempo continuo.','Manual es otra clasificación.','Estacionario trata constancia temporal.'],'Ecuación diferencial → tiempo continuo.'),
op('Desacoplados','twin-tanks.jpg','Debes justificar la ausencia de influencia entre variables.',[
'Da un ejemplo de sistemas desacoplados y argumenta.','Propón dos subsistemas independientes y explica por qué están desacoplados.','Describe un par de sistemas cuyas variables no se afecten entre sí y justifica la clasificación.','Da un caso real de desacoplamiento y demuestra que no existe influencia entre variables.'],'Ejemplo: dos circuitos RC independientes, cada uno con su propia fuente y sin conexión entre ellos; las variables de uno no influyen en las del otro.',['Dos sistemas o subsistemas.','Sin influencia entre sus variables.','La justificación debe explicar esa independencia.'],'Desacoplado = sin relación entre variables.'),
mc('Proceso','line.jpg','La operación avanza mediante cambios sucesivos.',[
'¿Qué concepto se define como una operación marcada por cambios graduales que suceden progresivamente?','¿Cómo se llama una operación formada por una secuencia progresiva de cambios?','Si el interés está en la transformación que ocurre paso a paso, ¿qué concepto corresponde?','Una serie ordenada de cambios que conduce a un resultado se denomina…'],['Planta','Proceso','Sistema físico','Set-point'],1,['Planta es el equipo físico.','Correcto: esa es la definición de proceso.','Sistema físico es una clasificación del conjunto material.','Set-point es una referencia.'],'Algo que ocurre y progresa = proceso.'),
mc('Planta / proceso / sistema','printer.jpg','La imagen muestra una impresora 3D y su operación de fabricación.',[
'Si solo se señala el equipo físico de una impresora 3D, ¿qué concepto corresponde?','La estructura mecánica, extrusor y cama de impresión considerados como objeto físico son la…','¿Qué término describe el equipo físico de impresión, sin incluir la secuencia de fabricación?','Si se separa “equipo” de “operación”, el equipo de la impresora corresponde a la…'],['Proceso','Planta','Sistema','Salida'],1,['Proceso es la fabricación que ocurre.','Correcto: el hardware puede considerarse planta.','Sistema enfatiza el conjunto cooperante completo.','La salida sería la pieza obtenida.'],'Equipo físico, no operación.'),
mc('Proceso','printer.jpg','La pieza se forma capa por capa.',[
'La deposición sucesiva de material que convierte filamento en una pieza es…','¿Qué concepto describe la secuencia capa por capa de la impresión?','La transformación progresiva del filamento durante la fabricación corresponde al…','Si analizas “lo que ocurre” durante la impresión y no el equipo, estás analizando el…'],['Planta','Proceso','Sistema','Variable manipulada'],1,['Planta sería el equipo físico.','Correcto: es una operación progresiva.','Sistema sería el conjunto de componentes.','Variable manipulada es una acción de control.'],'Capa por capa = proceso.'),
mc('Sistema','printer.jpg','La impresora completa integra componentes para fabricar una pieza.',[
'Si se considera la impresora completa como componentes que trabajan juntos para fabricar, corresponde a…','Motor, extrusor, sensores y estructura trabajando para producir una pieza forman un…','¿Cómo se clasifica la impresora completa si interesa el conjunto y su objetivo?','El conjunto integrado de componentes de la impresora que cumple una función es un…'],['Proceso','Sistema','Señal discreta','Variable manipulada'],1,['Proceso es la secuencia de fabricación.','Correcto: se considera el conjunto cooperante.','Es una clasificación de señal.','Es una acción de control.'],'Conjunto completo + objetivo.'),
op('Lazo abierto','toaster.jpg','Debes producir ejemplos y justificar.',[
'Da tres ejemplos de sistemas de lazo abierto y argumenta.','Menciona tres sistemas sin realimentación y justifica uno.','Propón tres casos de lazo abierto y explica por qué la salida no corrige la acción en uno de ellos.','Da tres ejemplos distintos de control abierto y demuestra la ausencia de realimentación.'],'Ejemplos: tostador por tiempo, microondas por tiempo y licuadora operada por tiempo. Son de lazo abierto porque la salida obtenida no se mide para modificar automáticamente la acción durante el ciclo.',['Tres ejemplos.','Al menos una justificación.','La justificación debe mencionar que la salida no corrige la acción.'],'Lazo abierto: la salida no se usa para corregir.'),
mc('No estacionario','tank.jpg','El nivel cambia mientras transcurre el proceso.',[
'Si el nivel cambia con el tiempo durante el llenado, ¿qué comportamiento describe mejor al sistema en ese intervalo?','Durante el transitorio el nivel no permanece constante. ¿Cómo se clasifica ese comportamiento?','Una variable que evoluciona con el tiempo durante la operación indica un comportamiento…','Mientras la variable sigue cambiando y no está en régimen, el comportamiento es…'],['Estacionario','No estacionario','Desacoplado','SISO necesariamente'],1,['Estacionario implica permanencia temporal.','Correcto: la variable cambia con el tiempo.','Desacoplamiento es otra propiedad.','No se puede deducir SISO de este dato.'],'Pregunta si la variable permanece constante.'),
op('Estable y estacionario','stable.svg','Debes justificar dos propiedades diferentes.',[
'Da un ejemplo de un sistema estable y estacionario y argumenta.','Propón un caso que sea estable y además estacionario, justificando cada propiedad.','Describe un sistema en régimen que cumpla estabilidad y estacionariedad y explica ambas.','Da un ejemplo donde entrada acotada produzca salida acotada y, además, las variables permanezcan constantes en régimen.'],'Ejemplo: un circuito RC con entrada constante después de alcanzar régimen permanente. Es estable porque una entrada acotada produce una salida acotada y estacionario porque en régimen sus variables permanecen constantes.',['Explica estabilidad.','Explica estacionariedad.','No basta con nombrar un equipo.'],'Estable ≠ estacionario: justifica cada palabra.'),
mc('Estabilidad','stable.svg','La respuesta permanece acotada y converge.',[
'¿Qué propiedad representa mejor la respuesta mostrada?','Una salida oscila pero sus oscilaciones decrecen y no diverge. ¿Qué propiedad se observa?','Si una respuesta permanece limitada y converge, ¿qué término corresponde?','La gráfica no crece sin límite y se aproxima a una referencia. ¿Cómo se describe?'],['Inestabilidad','Estabilidad','MISO','Desacoplamiento'],1,['Inestable tendería a divergir o no permanecer acotado.','Correcto: la respuesta permanece acotada.','No se muestran entradas y salidas.','No se comparan subsistemas relacionados.'],'Entrada acotada → salida acotada.'),
mc('Sistema','robot.jpg','Varios elementos del robot cooperan para cumplir una función.',[
'¿La imagen ilustra mejor una planta, un proceso o un sistema si se considera el conjunto completo?','Motores, controladores, sensores y estructura del robot trabajando juntos forman un…','¿Qué concepto describe al robot completo cuando interesa su función global?','Si todos los subsistemas del robot se consideran como una unidad con un objetivo, hablamos de un…'],['Proceso','Sistema','Set-point','Perturbación'],1,['Proceso sería una secuencia de acciones.','Correcto: se considera el conjunto cooperante.','Set-point es un valor deseado.','Perturbación es una influencia externa.'],'Conjunto completo + función.'),
mc('Proceso','robot.jpg','Se considera una secuencia de acciones sucesivas.',[
'Observar, analizar opciones, decidir y actuar describe principalmente un…','Una secuencia organizada de acciones que conduce a un resultado se clasifica como…','Si el interés está en la sucesión de cambios y decisiones, ¿qué concepto corresponde?','Una operación que avanza paso a paso hasta producir una acción final es un…'],['Planta','Proceso','Sistema físico','Variable controlada'],1,['Planta es el equipo físico.','Correcto: es una serie progresiva de cambios o acciones.','Sistema físico describe un conjunto material.','Variable controlada es una magnitud.'],'Secuencia de acciones = proceso.'),
mc('Sistema de control','thermostat.jpg','El sistema regula su conducta o la de otro sistema.',[
'¿Qué concepto se define como componentes capaces de regular su propia conducta o la de otro sistema para lograr un funcionamiento predeterminado?','¿Cómo se llama el conjunto de componentes que regula el comportamiento para alcanzar una condición deseada?','Un conjunto que modifica su acción para conseguir un funcionamiento predeterminado constituye un…','¿Qué término corresponde a componentes cuya función es regular otro sistema o a sí mismos?'],['Sistema de control','Proceso','Planta','Señal discreta'],0,['Correcto: esa es la definición de sistema de control.','Proceso es una operación progresiva.','Planta es el equipo físico.','Señal discreta es una clasificación temporal.'],'La definición incluye “regular”.'),
mc('Sistema físico','robot.jpg','El equipo está compuesto por elementos materiales y energéticos.',[
'¿Cómo se llaman los sistemas compuestos por elementos materiales y energéticos que interactúan para cumplir una función específica?','Un sistema formado por materia y energía que interactúan pertenece a la categoría de…','¿Qué clasificación corresponde a una máquina real constituida por componentes materiales?','Si sus elementos son físicos y existe intercambio de energía, el sistema es…'],['Físicos','Abstractos','Estacionarios','Desacoplados'],0,['Correcto: esa es la definición de sistema físico.','Abstracto no se define por componentes materiales.','Estacionario es otra propiedad.','Desacoplado es otra propiedad.'],'Materiales + energía.'),
mc('Variable controlada','tank-control.svg','Los sensores observan el nivel del líquido.',[
'¿Qué variable se está controlando en la figura?','En el esquema de llenado y descarga, ¿cuál es la variable controlada?','La bomba y la descarga actúan para mantener una magnitud. ¿Cuál?','Si PV representa la magnitud regulada en el tanque, ¿qué variable corresponde?'],['Nivel del tanque','Velocidad de la bomba','Posición del panel','Tiempo de operación'],0,['Correcto: los sensores observan el nivel.','La bomba es parte de la actuación.','No es una variable del proceso.','El tiempo no es la magnitud indicada.'],'Busca la PV.'),
mc('Lazo cerrado','thermostat.jpg','La medición real se compara con un valor deseado.',[
'¿El sistema representa lazo abierto o cerrado si la temperatura medida se usa para corregir?','Si el controlador compara temperatura real con referencia y reajusta su acción, el lazo es…','¿Qué tipo de lazo existe cuando la salida medida regresa para modificar la acción?','Una medición de salida se realimenta y altera la señal de control. ¿Cómo se clasifica?'],['Lazo abierto','Lazo cerrado','MISO','Manual'],1,['Lazo abierto no usa la salida para corregir.','Correcto: existe realimentación.','MISO es una clasificación por entradas/salidas.','Manual trata intervención humana.'],'Salida medida usada para corregir.'),
mc('Aditividad','robot.jpg','La expresión compara respuesta a suma con suma de respuestas.',[
'La expresión x₁(t)+x₂(t) → y₁(t)+y₂(t) representa la propiedad de…','Si la respuesta a x₁+x₂ es igual a la suma de las respuestas individuales, se cumple…','¿Qué propiedad de linealidad se verifica al sumar dos entradas y obtener la suma de sus salidas?','y(x₁+x₂)=y(x₁)+y(x₂) corresponde a…'],['Proporcionalidad','Aditividad','Estabilidad','Estacionariedad'],1,['Proporcionalidad usa escalamiento por una constante.','Correcto: esa es la propiedad de aditividad.','Estabilidad trata acotamiento.','Estacionariedad trata constancia temporal.'],'La operación principal es sumar.'),
mc('Acoplamiento','twin-tanks.jpg','Los tanques están conectados de manera que uno puede afectar al otro.',[
'Dos tanques conectados comparten flujo y el nivel de uno influye en el otro. ¿Cómo se clasifican?','Si una variación en el primer tanque modifica el segundo, los subsistemas están…','¿Qué propiedad existe cuando las variables de dos subsistemas se influyen mutuamente?','La conexión hidráulica hace que un cambio en un tanque afecte al otro. Esto indica…'],['Desacoplados','Acoplados','Estacionarios','SISO necesariamente'],1,['Desacoplados implicaría ausencia de influencia.','Correcto: existe relación entre variables.','La conexión no implica constancia.','No se puede deducir SISO solo de esto.'],'Acoplado = existe influencia entre variables.'),
mc('SISO / MIMO','robot.jpg','La clasificación depende del número de variables consideradas.',[
'Un controlador recibe una referencia y entrega una sola salida medida. ¿Cómo se clasifica?','Si el modelo tiene exactamente una entrada y una salida, corresponde a…','Una sola señal entra y una sola señal sale del bloque. ¿Qué sigla aplica?','¿Cuál clasificación corresponde a Single Input, Single Output?'],['SISO','SIMO','MISO','MIMO'],0,['Correcto: una entrada y una salida.','SIMO tiene una entrada y varias salidas.','MISO tiene varias entradas y una salida.','MIMO tiene varias entradas y varias salidas.'],'Una entrada + una salida.'),
mc('SISO / MIMO','robot.jpg','Una celda robótica puede tener varias referencias y varias salidas.',[
'Si una celda robótica recibe varias referencias y se observan varias salidas, ¿cómo se clasifica?','Múltiples entradas y múltiples salidas corresponden a…','Un modelo considera posición, velocidad y fuerza como varias entradas y varias salidas. ¿Qué sigla aplica?','¿Qué clasificación describe Multiple Input, Multiple Output?'],['SISO','SIMO','MISO','MIMO'],3,['SISO tiene una entrada y una salida.','SIMO tiene una entrada y varias salidas.','MISO tiene varias entradas y una salida.','Correcto: múltiples entradas y múltiples salidas.'],'Múltiples entradas + múltiples salidas.'),
mc('Proporcionalidad','robot.jpg','Se analiza una de las condiciones de linealidad.',[
'Si al duplicar la entrada se duplica exactamente la salida, ¿qué propiedad se verifica?','¿Qué propiedad se cumple cuando y(kx)=k·y(x)?','Al multiplicar la entrada por una constante, la salida cambia por la misma constante. Esto es…','El escalamiento de la respuesta en la misma proporción que la entrada corresponde a…'],['Aditividad','Proporcionalidad','Estabilidad','Acoplamiento'],1,['Aditividad se refiere a suma de entradas.','Correcto: es proporcionalidad u homogeneidad.','Estabilidad no describe escalamiento.','Acoplamiento es relación entre subsistemas.'],'Busca la propiedad asociada a multiplicar por una constante.'),
mc('Dinámico / estático','tank.jpg','El tanque almacena líquido y por ello conserva información de su estado previo.',[
'El nivel actual depende del volumen acumulado anteriormente. ¿El sistema es estático o dinámico?','Si la salida depende del estado previo además de la entrada actual, el sistema es…','Un tanque tiene memoria por almacenamiento. ¿Qué clasificación corresponde?','¿Qué tipo de sistema presenta dependencia de condiciones pasadas?'],['Estático','Dinámico','Desacoplado','Manual'],1,['Estático no depende de estados previos.','Correcto: existe memoria o dependencia temporal.','Desacoplado es otra propiedad.','Manual trata intervención humana.'],'¿El presente depende del pasado?'),
mc('Referencia','thermostat.jpg','La referencia es el valor deseado.',[
'En un termostato, el valor objetivo seleccionado por el usuario es el…','¿Cómo se llama el valor deseado contra el que se compara la medición?','El controlador intenta llevar la salida a 22 °C. Ese 22 °C es la…','¿Qué término corresponde al valor de destino de la variable controlada?'],['Salida','Set-point o referencia','Variable manipulada','Perturbación'],1,['La salida es el valor realmente obtenido.','Correcto: es el valor deseado.','Es la acción que modifica el controlador.','Es una influencia externa.'],'Valor deseado = set-point.'),
mc('Perturbación','tank.jpg','Una perturbación altera el proceso sin ser la acción de control deseada.',[
'Una variación externa de caudal que cambia el nivel sin ser ordenada por el controlador es una…','¿Cómo se llama una influencia no deseada que modifica la salida del sistema?','Si aparece una entrada externa que altera el proceso y no forma parte de la acción de control, se trata de una…','Un cambio ambiental que afecta la variable controlada sin ser el set-point corresponde a…'],['Referencia','Perturbación','Variable manipulada','Salida'],1,['Referencia es el valor deseado.','Correcto: es una influencia externa no deseada.','Variable manipulada es la acción del controlador.','Salida es el resultado observado.'],'Influencia externa no ordenada.'),
mc('Trampa conceptual','thermostat.jpg','Automático y lazo cerrado no son sinónimos.',[
'Una máquina ejecuta automáticamente una secuencia programada. ¿Eso basta para afirmar que es lazo cerrado?','Si un sistema funciona sin intervención humana, ¿puede concluirse automáticamente que usa realimentación?','Un ciclo automático por tiempo no mide la salida. ¿Qué afirmación es correcta?','¿Qué dato falta para decidir si un sistema automático es de lazo cerrado?'],['Sí, porque es automático','No; hay que saber si la salida se usa para corregir','Sí, porque tiene controlador','No; primero hay que saber si es SISO'],1,['Automático no implica realimentación.','Correcto: el criterio es usar la salida para corregir.','Tener controlador tampoco demuestra cierre de lazo.','SISO/MIMO es una clasificación diferente.'],'Automático ≠ lazo cerrado.'),
mc('Estable / estacionario','stable.svg','Durante el transitorio la salida cambia pero permanece acotada.',[
'Durante un transitorio la salida cambia, pero permanece acotada y converge. ¿Cuál afirmación es correcta?','Una respuesta varía con el tiempo sin divergir. ¿Qué relación entre estabilidad y estacionariedad es posible?','Si el sistema todavía cambia durante el transitorio pero la salida se mantiene limitada, ¿qué puede afirmarse?','¿Cuál opción distingue correctamente estabilidad de estacionariedad durante un transitorio?'],['Puede ser estable aunque aún no sea estacionaria','Si es estable debe ser estacionaria en todo momento','Si cambia con el tiempo es inestable','La gráfica demuestra MISO'],0,['Correcto: estabilidad no exige constancia durante el transitorio.','Son propiedades distintas.','Cambiar no significa divergir.','No se muestran entradas y salidas.'],'No confundas “cambiar” con “divergir”.'),
mc('Planta / proceso / sistema','printer.jpg','Un mismo caso puede analizarse desde varias perspectivas.',[
'¿Qué relación es correcta para una impresora 3D?','Elige la combinación que distingue correctamente conjunto, equipo físico y operación en impresión 3D.','¿Cuál opción asigna de forma correcta sistema, planta y proceso?','En una impresora 3D, ¿qué combinación conceptual es la más precisa?'],['Impresora completa = sistema; hardware = planta; fabricación capa por capa = proceso','Pieza final = planta; filamento = sistema; software = proceso','Archivo = planta; extrusor = proceso; pieza = sistema','Los tres términos son sinónimos'],0,['Correcto: distingue conjunto, equipo físico y operación.','La pieza es salida y el filamento es insumo.','Las categorías están invertidas.','No son sinónimos.'],'Conjunto / equipo / operación.')
];