(()=>{
const V=Math.max(1,Math.min(4,Number(window.STUDY_VERSION||1)))-1;
const B=[[],[],[],[]];
const add=(...qs)=>qs.forEach((q,i)=>B[i].push(q));
const mc=(kind,scene,caption,q,options,correct,why,hint)=>({type:'mcq',kind,scene,caption,q,options,correct,why,hint});
const op=(kind,scene,caption,q,model,criteria,hint)=>({type:'open',kind,scene,caption,q,model,criteria,hint});
const none='none';

// 1. Imagen -> tipo de señal
add(
mc('Señales','signal-sampled','Señal muestreada','¿La imagen muestra una señal de qué tipo?',['Continua','Discreta','Estacionaria','MIMO'],1,['La curva no existe en todos los instantes; solo hay muestras.','Correcto: los valores aparecen en instantes separados.','Estacionaria describe otra propiedad.','MIMO clasifica entradas y salidas.'],'Observa si la señal existe en todo instante o solo en muestras.'),
mc('Señales','signal-continuous','Temperatura registrada continuamente','¿La señal ilustrada se clasifica como…',['Discreta','Continua','SISO','Estática'],1,['No está formada por muestras aisladas.','Correcto: se define para cualquier instante de tiempo.','SISO no clasifica la forma temporal.','Estática describe memoria, no continuidad temporal.'],'Fíjate si puedes asignar un valor a cualquier instante.'),
mc('Señales','signal-pulses','Conteo de piezas','La señal de la imagen, generada por el paso individual de piezas, es de tipo…',['Continua','Discreta','Lineal','Acoplada'],1,['Los eventos no existen en todo instante.','Correcto: cada pieza genera un evento separado.','Linealidad es otra propiedad.','Acoplamiento describe interacción entre subsistemas.'],'Cada evento produce una muestra.'),
mc('Señales','signal-samples-temp','Muestras de temperatura','¿Qué tipo de señal representa la imagen si el sensor guarda una lectura cada segundo?',['Continua','Discreta','Estacionaria','No lineal'],1,['La variable física puede ser continua, pero el registro no.','Correcto: el registro existe en instantes separados.','No se deduce estacionariedad del muestreo.','No se deduce linealidad del muestreo.'],'Clasifica el registro, no la variable física.')
);

// 2. Definición -> variable manipulada
add(
mc('Conceptos',none,'','Es la cantidad o condición que el controlador modifica para afectar el valor de la variable controlada. Se conoce como…',['Variable manipulada','Variable controlada','Perturbación','Set-point'],0,['Correcto: es la acción que modifica el controlador.','Es la magnitud que se desea regular.','Es una influencia externa no deseada.','Es el valor de referencia.'],'¿Qué variable cambia directamente el controlador?'),
mc('Conceptos',none,'','La magnitud que el controlador altera directamente para provocar un cambio en la salida es la…',['Referencia','Variable manipulada','Variable controlada','Perturbación'],1,['La referencia indica el objetivo.','Correcto: es la acción de control.','Es la magnitud regulada.','No es una acción ordenada por el controlador.'],'Busca la acción de control.'),
mc('Conceptos',none,'','Cuando un controlador cambia el voltaje, la apertura de una válvula o la potencia de un calentador, esas magnitudes cumplen el papel de…',['Variables manipuladas','Variables controladas','Salidas deseadas','Perturbaciones'],0,['Correcto: son magnitudes modificadas para influir en el proceso.','Son las que se pretende regular.','Una salida deseada corresponde a referencia.','No son influencias externas.'],'Son magnitudes que el controlador ordena modificar.'),
mc('Conceptos',none,'','¿Cómo se llama la variable sobre la que actúa el controlador para llevar la variable controlada hacia su valor deseado?',['Set-point','Variable manipulada','Salida medida','Error'],1,['Es el objetivo, no la acción.','Correcto: es la acción aplicada al sistema.','Es la variable observada.','Es la diferencia entre referencia y salida.'],'Distingue objetivo, medición y acción.')
);

// 3. MISO, ejemplo argumentado
add(
op('MISO','miso-mixer','Mezclador con varios sensores y una válvula','Da un ejemplo de un sistema MISO y argumenta por qué lo es.','Un mezclador recibe temperatura, pH y nivel como entradas y genera una sola orden hacia una válvula dosificadora. Es MISO porque tiene múltiples entradas y una sola salida.',['Menciona más de una entrada.','Menciona una sola salida.','Justifica contando entradas y salidas.'],'MISO = Multiple Input, Single Output.'),
op('MISO','miso-hvac','Ventilación con tres mediciones y un ventilador','Da un ejemplo de un sistema MISO aplicado a climatización y argumenta.','Temperatura, humedad y CO₂ entran al controlador; éste genera una sola orden de velocidad para el ventilador. Varias entradas y una salida: MISO.',['Varias entradas identificadas.','Una salida identificada.','Explicación de la clasificación.'],'No confundas número de sensores con número de salidas.'),
op('MISO','miso-irrigation','Riego con varios sensores y una electroválvula','Propón un sistema MISO de riego y explica su clasificación.','Humedad del suelo, temperatura y radiación son entradas; la única salida es la orden de apertura de una electroválvula.',['Más de una entrada.','Una sola salida.','Argumento explícito.'],'Cuenta señales, no componentes.'),
op('MISO','miso-battery','Batería: voltaje, corriente y temperatura hacia una decisión','Construye un ejemplo MISO relacionado con una batería y argumenta.','Voltaje, corriente y temperatura son entradas del controlador y éste genera una sola señal para limitar la carga.',['Varias entradas.','Una salida.','Justificación por número de señales.'],'MISO no significa varios actuadores.')
);

// 4. Planta/proceso/sistema con imagen
add(
mc('Planta / proceso / sistema','industrial-plant','Instalación industrial física','La instalación industrial mostrada se considera principalmente ejemplo de…',['Proceso','Planta','Set-point','Señal'],1,['Proceso sería la operación que ocurre dentro de ella.','Correcto: se muestra el equipo físico donde ocurre la operación.','No es un valor deseado.','No es una señal.'],'Se pregunta por el objeto físico.'),
mc('Planta / proceso / sistema','water-plant','Planta de tratamiento de agua','La imagen muestra el conjunto físico de tanques, bombas y tuberías. ¿Cómo se clasifica principalmente?',['Planta','Proceso','Perturbación','Variable'],0,['Correcto: es el conjunto físico donde se desarrolla la operación.','Proceso sería la secuencia de tratamiento.','No es una influencia externa.','Es más que una sola magnitud.'],'Objeto físico = planta.'),
mc('Planta / proceso / sistema','bottling-plant','Línea física de embotellado','Si observas máquinas, transportadores y llenadoras como instalación física, el ejemplo corresponde a…',['Sistema únicamente','Planta','Proceso','Referencia'],1,['Puede formar parte de un sistema, pero aquí se enfatiza la instalación física.','Correcto: se pregunta por la instalación física.','Proceso sería la secuencia de llenar, tapar y etiquetar.','No es un valor objetivo.'],'¿Instalación o secuencia de cambios?'),
mc('Planta / proceso / sistema','refinery','Refinería e instalaciones de proceso','La instalación ilustrada, considerada como equipo físico donde se realiza la transformación, es una…',['Planta','Proceso','Salida','Perturbación'],0,['Correcto: es la instalación física.','Proceso es la transformación que ocurre en ella.','No es un resultado del sistema.','No es una influencia externa.'],'La palabra clave es instalación física.')
);

// 5. Sistemas manuales
add(
mc('Clasificación',none,'','Son aquellos sistemas donde se requiere una persona para ejecutar una acción que indica al sistema qué hacer. Son sistemas…',['Automáticos','Manuales','Continuos','MIMO'],1,['Automático ejecuta la acción sin intervención humana directa.','Correcto: la persona interviene para ejecutar la acción.','Continuo clasifica el tiempo.','MIMO clasifica entradas y salidas.'],'La definición gira alrededor de la intervención humana.'),
mc('Clasificación',none,'','Un sistema depende de que un operador accione físicamente un mando para ejecutar cada acción. Se clasifica como…',['Manual','Automático','Estacionario','Lazo cerrado'],0,['Correcto: necesita intervención humana directa.','No ejecuta por sí solo.','Estacionariedad es otra propiedad.','Manual no determina por sí mismo el tipo de lazo.'],'¿Quién ejecuta la acción?'),
mc('Clasificación',none,'','Si el funcionamiento requiere que una persona decida y accione directamente el mecanismo, se trata de un sistema…',['Discreto','Manual','Acoplado','Automático'],1,['Discreto describe el tiempo o señal.','Correcto: la persona realiza la acción.','Acoplado describe interacción entre subsistemas.','No actúa automáticamente.'],'Intervención humana directa.'),
mc('Clasificación',none,'','¿Qué nombre recibe un sistema que no ejecuta la acción hasta que un operador manipula directamente su control?',['Manual','Automático','Dinámico','SISO'],0,['Correcto.','Automático no requiere esa acción humana directa.','Dinámico habla de dependencia temporal.','SISO habla de entradas y salidas.'],'Concéntrate en quién realiza la acción.')
);

// 6. Lazo cerrado: qué debe existir para corregir
add(
mc('Lazo cerrado','feedback-motor','Motor con sensor de velocidad y realimentación','Según la lógica de un sistema en lazo cerrado, ¿qué debe estar presente para que el actuador corrija la salida?',['Realimentación de la salida medida','Solo un temporizador','Únicamente el set-point','Una perturbación'],0,['Correcto: la salida medida debe regresar para calcular el error.','Un temporizador no informa el resultado real.','La referencia sola no permite saber el error.','Una perturbación no es requisito del lazo.'],'Para corregir debes conocer qué ocurrió en la salida.'),
mc('Lazo cerrado','feedback-tank','Tanque con medición de nivel','Para que el actuador corrija el nivel en un lazo cerrado, el controlador necesita recibir…',['El nivel medido','Solo la orden inicial','El diámetro del tanque','El tiempo transcurrido'],0,['Correcto: la salida medida se realimenta.','No informa el resultado actual.','Es un parámetro físico, no realimentación.','No sustituye la medición de salida.'],'Salida medida → controlador.'),
mc('Lazo cerrado','feedback-temp','Horno con sensor de temperatura','En lazo cerrado, ¿qué permite decidir si debe aumentar o disminuir la potencia del calentador?',['La temperatura real medida','La potencia nominal del equipo','La marca del sensor','Solo el valor deseado'],0,['Correcto: permite comparar salida real con referencia.','No indica el error actual.','No participa en la lógica.','La referencia sola no informa la salida.'],'Se necesita comparar referencia contra salida real.'),
mc('Lazo cerrado','feedback-position','Servomotor con sensor de posición','Para corregir la posición de un servomotor en lazo cerrado debe regresar al controlador…',['La posición medida','El nombre del motor','Solo la señal de mando','El tiempo de encendido'],0,['Correcto: la realimentación permite calcular el error.','No es información de control.','Es acción, no realimentación.','No describe la posición actual.'],'La salida debe medirse y volver al controlador.')
);

// 7. Definición de sistema
add(
mc('Sistema',none,'','Es una combinación de componentes que actúan juntos y realizan un objetivo determinado. La definición corresponde a…',['Proceso','Sistema','Planta','Perturbación'],1,['Proceso es una sucesión de cambios.','Correcto: componentes que cooperan para un objetivo.','Planta es el equipo físico sobre el que actúa el control.','Perturbación es una influencia externa.'],'Componentes + interacción + objetivo.'),
mc('Sistema',none,'','Un conjunto de elementos relacionados que trabajan de manera coordinada para cumplir una función se denomina…',['Sistema','Proceso','Referencia','Variable'],0,['Correcto.','Proceso enfatiza una secuencia de cambios.','Referencia es un valor deseado.','Variable es una magnitud.'],'Busca el concepto que agrupa elementos coordinados.'),
mc('Sistema',none,'','¿Qué concepto describe varios componentes que interactúan entre sí con un propósito común?',['Planta','Sistema','Señal','Error'],1,['Planta enfatiza el objeto físico.','Correcto.','Señal es información.','Error es una diferencia.'],'Interacción de componentes para un objetivo.'),
mc('Sistema',none,'','Cuando distintos componentes actúan conjuntamente para realizar un objetivo, forman un…',['Proceso','Sistema','Set-point','Actuador'],1,['Proceso describe cambios sucesivos.','Correcto.','Set-point es referencia.','Actuador es solo un componente.'],'El concepto abarca al conjunto completo.')
);

// 8. Tres elementos base de lógica de control
add(
mc('Lógica de control',none,'','¿Cuáles son los tres elementos base que debes identificar en la lógica de un sistema de control?',['Variable a controlar, actuador y set-point','Planta, proceso y sensor','Entrada, perturbación y pantalla','Sensor, operador y salida'],0,['Correcto: qué regulas, con qué actúas y hacia qué valor.','No corresponde a la terna pedida.','No incluye la acción y referencia como se requiere.','No es la base lógica solicitada.'],'Qué controlas + quién actúa + a qué valor quieres llegar.'),
mc('Lógica de control',none,'','Para plantear la lógica básica de regulación, ¿qué conjunto identifica correctamente los tres elementos esenciales?',['Variable controlada, actuador y referencia','Entrada, salida y perturbación','Planta, sensor y operador','Proceso, salida y error'],0,['Correcto.','Son señales/condiciones, pero no la terna solicitada.','No define la lógica mínima.','No incluye el elemento de actuación.'],'Variable, acción y objetivo.'),
mc('Lógica de control',none,'','En una regulación de velocidad, los tres elementos base equivalen a identificar…',['Velocidad a controlar, actuador y velocidad deseada','Motor, eje y carcasa','Sensor, pantalla y operador','Entrada, ruido y salida'],0,['Correcto: variable, actuador y referencia.','Son componentes físicos.','No representa la lógica mínima.','No incluye el actuador ni set-point.'],'Traduce la terna al caso concreto.'),
mc('Lógica de control',none,'','¿Qué combinación resume la estructura lógica mínima para regular una magnitud?',['Magnitud controlada, elemento actuador y set-point','Planta, proceso y perturbación','Sensor, pantalla y alarma','Entrada, salida y tiempo'],0,['Correcto.','No es la terna solicitada.','Son componentes auxiliares.','No identifica la acción ni referencia.'],'Controlada + actuador + referencia.')
);

// 9. Manipulada vs salida
add(
mc('Variables',none,'','¿La variable manipulada es conocida también como la salida del sistema?',['Sí, siempre','No; es la acción que se modifica para afectar la salida','Solo en sistemas SISO','Solo en lazo abierto'],1,['Confunde acción con resultado.','Correcto: manipulada y salida/controlada cumplen papeles distintos.','SISO no las vuelve equivalentes.','El tipo de lazo no cambia la definición.'],'Acción aplicada ≠ resultado obtenido.'),
mc('Variables',none,'','¿Es correcto llamar “salida” a la apertura de una válvula cuando esa apertura es lo que el controlador modifica para regular nivel?',['Sí','No; es variable manipulada','Solo si existe sensor','Solo si el tanque es dinámico'],1,['La salida regulada sería el nivel.','Correcto.','Un sensor no cambia el papel de la variable.','Ser dinámico no cambia la definición.'],'Distingue acción de control y variable regulada.'),
mc('Variables',none,'','En un motor, el voltaje aplicado se modifica para controlar la velocidad. ¿Voltaje y velocidad son la misma variable?',['Sí','No; voltaje es manipulada y velocidad es controlada/salida','Solo a velocidad constante','Solo en lazo cerrado'],1,['Son magnitudes con funciones distintas.','Correcto.','La condición no las hace equivalentes.','El lazo tampoco.'],'Causa aplicada y resultado son variables distintas.'),
mc('Variables',none,'','Si la potencia del calentador se ajusta para regular temperatura, ¿puede decirse que la potencia es la salida controlada?',['Sí, porque cambia','No; la potencia es manipulada y la temperatura es la salida controlada','Solo si hay termostato','Solo si el sistema es continuo'],1,['Cambiar no significa ser la salida controlada.','Correcto.','El sensor no cambia sus roles.','La continuidad temporal tampoco.'],'Qué modifica el controlador vs qué desea regular.')
);

// 10. Imagen -> clasificación de sistema (dinámico/estático)
add(
mc('Clasificación','tank-dynamic','Nivel que cambia conforme entra y sale líquido','Análogamente, ¿la imagen representa un sistema de tipo…',['Estático','Dinámico','Desacoplado necesariamente','SISO necesariamente'],1,['El estado del tanque depende de su evolución previa.','Correcto: el nivel cambia con el tiempo y existe almacenamiento.','No se deduce desacoplamiento.','No se deduce el número total de señales.'],'Observa si el estado evoluciona con el tiempo.'),
mc('Clasificación','oven-dynamic','Temperatura del horno evolucionando con el tiempo','¿Qué clasificación temporal representa el sistema ilustrado?',['Dinámico','Estático','MISO necesariamente','Desacoplado'],0,['Correcto: la temperatura evoluciona y depende del estado previo.','No responde instantáneamente sin memoria.','No puede deducirse solo de la imagen.','No es la propiedad mostrada.'],'Hay almacenamiento de energía y evolución temporal.'),
mc('Clasificación','motor-dynamic','Motor acelerando hasta alcanzar velocidad','La escena muestra una velocidad que cambia hasta estabilizarse. El sistema es…',['Estático','Dinámico','Estacionario por definición','SIMO'],1,['Un sistema estático no tiene evolución temporal interna.','Correcto.','Dinámico no implica necesariamente estacionario.','No se pregunta número de salidas.'],'La respuesta tarda en evolucionar.'),
mc('Clasificación','reservoir-dynamic','Depósito cuyo nivel varía durante el llenado','El depósito ilustrado se clasifica como sistema…',['Dinámico','Estático','Lineal necesariamente','MIMO necesariamente'],0,['Correcto: almacena materia y su nivel depende del tiempo.','No responde sin memoria.','No puede afirmarse linealidad por la imagen.','No se conoce el número de señales.'],'Almacenamiento + evolución = dinámico.')
);

// 11. Imagen I/O
add(
mc('Entradas / salidas','simo-one-four','Una entrada y cuatro salidas','La imagen representa un sistema descrito según su número de entradas y salidas. ¿Cómo se clasifica?',['SISO','SIMO','MISO','MIMO'],1,['SISO tendría una sola salida.','Correcto: Single Input, Multiple Output.','MISO tendría varias entradas y una salida.','MIMO tendría varias entradas y varias salidas.'],'Cuenta las flechas que entran y salen.'),
mc('Entradas / salidas','miso-three-one','Tres entradas y una salida','Según el número de entradas y salidas mostrado, el sistema es…',['SIMO','MISO','SISO','MIMO'],1,['SIMO sería una entrada y varias salidas.','Correcto: varias entradas y una salida.','SISO sería una y una.','MIMO tendría varias salidas.'],'Cuenta entradas y salidas por separado.'),
mc('Entradas / salidas','mimo-three-three','Tres entradas y tres salidas','¿Cómo se clasifica el sistema representado?',['MIMO','MISO','SIMO','SISO'],0,['Correcto: múltiples entradas y múltiples salidas.','Tendría una sola salida.','Tendría una sola entrada.','Tendría una entrada y una salida.'],'Varias + varias.'),
mc('Entradas / salidas','siso-one-one','Una entrada y una salida','La figura corresponde a un sistema…',['MISO','SIMO','SISO','MIMO'],2,['Requiere varias entradas.','Requiere varias salidas.','Correcto: una entrada y una salida.','Requiere varias de ambas.'],'Una y una.')
);

// 12. Figura -> lazo abierto/cerrado
add(
mc('Lazo abierto / cerrado','stove-timer','Estufa controlada por tiempo, sin medir cocción','La figura indica un ejemplo de sistema de…',['Lazo cerrado','Lazo abierto','MIMO','Desacoplado'],1,['No se realimenta el resultado de cocción.','Correcto: actúa sin medir la salida para corregirse.','No se pregunta número de señales.','No es la clasificación relevante.'],'¿La salida real vuelve al controlador?'),
mc('Lazo abierto / cerrado','toaster-timer','Tostador con temporizador','El sistema ilustrado funciona por tiempo y no mide el tostado real. ¿Es lazo abierto o cerrado?',['Lazo abierto','Lazo cerrado','Estacionario','Acoplado'],0,['Correcto: no usa la salida para corregir.','No existe realimentación del grado de tostado.','Otra clasificación.','Otra propiedad.'],'Temporizador ≠ realimentación.'),
mc('Lazo abierto / cerrado','washer-program','Lavadora que ejecuta un programa fijo sin medir limpieza','La figura representa, respecto a la corrección de la salida, un sistema de…',['Lazo cerrado','Lazo abierto','MISO','No estacionario necesariamente'],1,['No se mide la limpieza para corregir el ciclo.','Correcto: ejecuta la secuencia sin realimentar la salida relevante.','Otra clasificación.','No es lo preguntado.'],'¿Mide el resultado que desea obtener?'),
mc('Lazo abierto / cerrado','sprinkler-timer','Riego por temporizador','Un riego enciende 10 minutos por horario y no mide humedad del suelo. La figura representa…',['Lazo cerrado','Lazo abierto','SISO necesariamente','Sistema manual'],1,['No hay realimentación de humedad.','Correcto.','No se conoce toda la estructura de señales.','El temporizador ejecuta automáticamente.'],'No hay medición de la salida deseada.')
);

// 13. Ecuación diferencial + tiempo divisible
add(
mc('Tiempo continuo',none,'','Si el modelo del sistema está definido por una ecuación diferencial y el tiempo se considera infinitamente divisible, entonces se trata de un sistema…',['Discreto','Continuo','Estático','MIMO'],1,['Los sistemas discretos suelen modelarse en instantes separados.','Correcto: el tiempo continuo se modela típicamente con ecuaciones diferenciales.','Una ecuación diferencial implica evolución temporal.','MIMO no depende del tipo de tiempo.'],'Ecuación diferencial + t continuo.'),
mc('Tiempo continuo',none,'','Un modelo usa derivadas respecto al tiempo y supone que t puede tomar cualquier valor real. El sistema es…',['Continuo','Discreto','Desacoplado','Manual'],0,['Correcto.','Discreto trabaja en instantes separados.','No se deduce acoplamiento.','No se refiere a intervención humana.'],'Las derivadas son una pista clave.'),
mc('Tiempo continuo',none,'','¿Qué clasificación corresponde a un sistema descrito por ecuaciones diferenciales ordinarias en un eje temporal sin saltos?',['Continuo','Discreto','Estacionario necesariamente','SISO'],0,['Correcto.','Discreto implicaría instantes separados.','Continuidad no garantiza estacionariedad.','No describe entradas/salidas.'],'Piensa en el dominio temporal.'),
mc('Tiempo continuo',none,'','Si una variable de estado evoluciona para todo instante t y su modelo incluye dx/dt, se trata de un sistema…',['Discreto','Continuo','Estático','SIMO'],1,['No existe solo en muestras.','Correcto.','dx/dt implica dinámica.','No se conoce el número de salidas.'],'dx/dt indica tiempo continuo.')
);

// 14. Desacoplado, ejemplo argumentado
add(
op('Desacoplamiento','decoupled-tanks','Dos tanques independientes','Da un ejemplo de un sistema desacoplado y argumenta.','Dos tanques con entradas y salidas independientes, sin tubería ni intercambio entre ellos. Cambiar el nivel de uno no modifica el otro; por eso están desacoplados.',['Dos subsistemas identificados.','Ausencia de interacción entre ellos.','Explica que cambiar uno no afecta al otro.'],'Desacoplado = un subsistema no altera al otro.'),
op('Desacoplamiento','decoupled-motors','Dos motores con controles independientes','Propón un ejemplo de sistema desacoplado y justifica.','Dos motores con alimentación y control independientes. Variar la velocidad de uno no modifica la respuesta del otro.',['Identificar subsistemas.','Independencia de efectos.','Argumentación clara.'],'Busca independencia entre subsistemas.'),
op('Desacoplamiento','decoupled-rooms','Dos habitaciones con climatización independiente','Da un ejemplo desacoplado aplicado a control de temperatura y argumenta.','Dos cámaras térmicamente aisladas, cada una con su propio calentador y sensor. La acción en una no cambia la temperatura de la otra.',['Dos subsistemas.','Sin influencia mutua significativa.','Justificación.'],'Si uno cambia, el otro debe permanecer esencialmente igual.'),
op('Desacoplamiento','decoupled-lines','Dos bandas de producción independientes','Construye un ejemplo de sistema desacoplado en manufactura.','Dos bandas con motores, sensores y material independientes. Una puede detenerse o cambiar velocidad sin alterar la otra.',['Dos subsistemas.','Acciones independientes.','Explicación del desacoplamiento.'],'No debe existir interacción relevante entre las líneas.')
);

// 15. Definición proceso
add(
mc('Proceso',none,'','¿Qué se define como una operación marcada por una serie de cambios graduales que suceden unos tras otros de forma progresiva?',['Planta','Proceso','Sistema','Set-point'],1,['Planta es el equipo físico.','Correcto: describe una sucesión progresiva de cambios.','Sistema es un conjunto de componentes.','Set-point es referencia.'],'La clave es “serie de cambios”.'),
mc('Proceso',none,'','Una sucesión ordenada de transformaciones que ocurren progresivamente corresponde a un…',['Proceso','Sistema','Actuador','Sensor'],0,['Correcto.','Sistema enfatiza componentes relacionados.','Actuador ejecuta una acción.','Sensor mide.'],'Transformaciones sucesivas.'),
mc('Proceso',none,'','¿Qué concepto se refiere a una operación en la que ocurren cambios graduales uno tras otro?',['Proceso','Planta','Variable','Controlador'],0,['Correcto.','Planta es el objeto físico.','Variable es una magnitud.','Controlador es un componente.'],'Operación progresiva.'),
mc('Proceso',none,'','La secuencia calentar → evaporar → condensar → enfriar es principalmente ejemplo de un…',['Sistema','Proceso','Set-point','Sensor'],1,['Sistema sería el conjunto de equipos.','Correcto: es una secuencia de cambios.','No es una referencia.','No es un elemento de medición.'],'Se está describiendo lo que sucede, no el equipo.')
);

// 16. Imágenes -> planta/proceso/sistema
add(
mc('Planta / proceso / sistema','industrial-pair','Dos instalaciones industriales','Las instalaciones mostradas se consideran principalmente ejemplos de…',['Proceso','Planta','Señal','Referencia'],1,['Proceso sería lo que ocurre dentro de ellas.','Correcto: son instalaciones físicas.','No representan señales.','No son valores deseados.'],'Se muestran objetos físicos industriales.'),
mc('Planta / proceso / sistema','machine-pair','Dos máquinas de producción','Las dos máquinas mostradas, vistas como equipos físicos donde ocurre una operación, son ejemplos de…',['Planta','Proceso','Perturbación','Error'],0,['Correcto.','Proceso sería la transformación realizada.','No son influencias externas.','No representan una diferencia.'],'Equipo físico = planta.'),
mc('Planta / proceso / sistema','lab-pair','Dos montajes físicos de laboratorio','¿Cómo se clasifican principalmente los montajes físicos ilustrados?',['Proceso','Planta','Set-point','Salida'],1,['Proceso sería la secuencia experimental.','Correcto: son objetos físicos sobre los que se actúa.','No son valores de referencia.','No son resultados por sí mismos.'],'Se pregunta por el montaje físico.'),
mc('Planta / proceso / sistema','production-pair','Dos instalaciones de manufactura','Las instalaciones de manufactura ilustradas son ejemplos de…',['Planta','Proceso','Variable controlada','Perturbación'],0,['Correcto.','Proceso sería la sucesión de operaciones.','No son una magnitud.','No son una influencia externa.'],'Observa que son instalaciones físicas.')
);

// 17. Segunda definición de proceso, como guía
add(
mc('Proceso',none,'','Una operación formada por cambios graduales y progresivos que se suceden unos tras otros recibe el nombre de…',['Sistema','Proceso','Planta','Control'],1,['Sistema es el conjunto organizado.','Correcto.','Planta es el equipo físico.','Control es la acción de regulación.'],'La guía repite esta definición: recuerda el término exacto.'),
mc('Proceso',none,'','¿Cuál concepto coincide con “serie progresiva de cambios que ocurren en una operación”?',['Proceso','Sistema físico','Entrada','Referencia'],0,['Correcto.','No describe necesariamente la secuencia.','Entrada es una señal o condición.','Referencia es un valor deseado.'],'Serie progresiva de cambios.'),
mc('Proceso',none,'','Cuando interesa describir cómo una materia cambia etapa por etapa, se está describiendo principalmente un…',['Proceso','Planta','Sensor','Actuador'],0,['Correcto.','Planta sería el equipo que contiene la transformación.','Sensor mide.','Actuador ejecuta.'],'Etapas sucesivas = proceso.'),
mc('Proceso',none,'','El término para una operación que avanza mediante transformaciones sucesivas es…',['Sistema','Proceso','Perturbación','Variable manipulada'],1,['Sistema abarca componentes.','Correcto.','Perturbación es externa.','Manipulada es una acción de control.'],'Piensa en la transformación, no en el equipo.')
);

// 18. Imagen -> planta/proceso/sistema
add(
mc('Planta / proceso / sistema','motorcycle','Motocicleta como objeto físico','¿La imagen ilustra principalmente una planta, un proceso o un sistema?',['Proceso','Planta','Set-point','Perturbación'],1,['No se muestra una secuencia de cambios.','Correcto: se muestra el objeto físico sobre el que podría actuar un control.','No es una referencia.','No es una influencia externa.'],'Se observa un objeto físico.'),
mc('Planta / proceso / sistema','elevator-object','Elevador como equipo físico','Considerando únicamente el equipo físico mostrado, ¿cómo se clasifica?',['Planta','Proceso','Error','Señal'],0,['Correcto.','Proceso sería el desplazamiento y sus etapas.','No es una diferencia.','No es información.'],'El objeto físico es la planta.'),
mc('Planta / proceso / sistema','cnc-machine','Máquina CNC','La máquina CNC mostrada, tomada como equipo sobre el que actúa el controlador, es una…',['Planta','Proceso','Referencia','Salida'],0,['Correcto.','Proceso sería el mecanizado.','No es valor deseado.','No es solo el resultado.'],'Equipo físico controlado.'),
mc('Planta / proceso / sistema','compressor','Compresor industrial','La imagen del compresor, considerado como objeto físico a controlar, representa una…',['Proceso','Planta','Perturbación','Variable'],1,['Proceso sería compresión como operación.','Correcto.','No es influencia externa.','No es una sola magnitud.'],'Objeto físico = planta.')
);

// 19. Tres ejemplos lazo abierto
add(
op('Lazo abierto','openloop-examples-a','Tostador, semáforo temporizado y riego por tiempo','Da tres ejemplos de sistemas de lazo abierto y argumenta.','Tostador por tiempo, semáforo con ciclo fijo y riego por temporizador. Son lazo abierto porque ejecutan la acción sin medir la salida relevante para corregirse.',['Tres ejemplos.','En cada uno no se realimenta la salida relevante.','Argumenta por ausencia de corrección basada en la salida.'],'No basta con que sea automático; debe faltar realimentación de la salida.'),
op('Lazo abierto','openloop-examples-b','Microondas, lavadora programada y iluminación horaria','Da tres ejemplos de lazo abierto distintos y justifica.','Microondas por tiempo, lavadora con programa fijo e iluminación por horario. Actúan según una orden/tiempo sin medir el resultado para corregirlo.',['Tres ejemplos.','Ausencia de realimentación.','Justificación clara.'],'Busca sistemas que ejecuten una orden sin comprobar el resultado.'),
op('Lazo abierto','openloop-examples-c','Secador temporizado, ventilador con selector y horno por tiempo','Menciona tres sistemas lazo abierto y explica por qué.','Secador por temporizador, ventilador con velocidad fija y horno por tiempo. No comparan la salida real con una referencia para corregirse.',['Tres ejemplos.','Explica falta de comparación salida-referencia.','Argumento correcto.'],'Temporizador o mando fijo suele ser pista, pero justifica por realimentación.'),
op('Lazo abierto','openloop-examples-d','Fuente temporizada, banda a velocidad fija y señal luminosa programada','Da tres ejemplos de sistemas lazo abierto y argumenta.','Fuente que opera por tiempo, banda a velocidad fija sin sensor y señal luminosa con secuencia programada. Ninguno mide la salida relevante para ajustar la acción.',['Tres ejemplos.','No hay medición de salida para corregir.','Explicación por cada caso o general.'],'La característica clave es la ausencia de realimentación de salida.')
);

// 20. Gráfico -> tipo de sistema (dinámico)
add(
mc('Interpretación gráfica','phase-change','Temperatura que evoluciona por etapas durante un calentamiento','Según el gráfico, ¿qué tipo de sistema se identifica por la evolución de la salida con el tiempo?',['Estático','Dinámico','Desacoplado','MISO'],1,['No responde instantáneamente sin memoria.','Correcto: la salida cambia con el tiempo y atraviesa distintas etapas.','No se muestra independencia entre subsistemas.','No se muestran varias entradas.'],'La gráfica muestra evolución temporal.'),
mc('Interpretación gráfica','tank-fill-graph','Nivel de tanque durante llenado y descarga','El gráfico de nivel frente al tiempo corresponde a un comportamiento de sistema…',['Dinámico','Estático','SISO necesariamente','Manual'],0,['Correcto: el estado cambia con el tiempo.','No es una relación instantánea.','No se deduce el número de señales.','No se deduce intervención humana.'],'Hay almacenamiento y evolución temporal.'),
mc('Interpretación gráfica','motor-speed-graph','Velocidad durante arranque y frenado','Según la gráfica de velocidad vs. tiempo, el sistema es principalmente…',['Estático','Dinámico','Desacoplado','SIMO'],1,['Un estático no presenta esta evolución temporal.','Correcto.','No habla de interacción entre subsistemas.','No habla de número de salidas.'],'La salida tiene transitorio.'),
mc('Interpretación gráfica','oven-heat-graph','Temperatura durante calentamiento y enfriamiento','La gráfica muestra una salida que evoluciona gradualmente con el tiempo. ¿Qué clasificación corresponde?',['Dinámico','Estático','MIMO','Acoplado necesariamente'],0,['Correcto.','No responde instantáneamente.','No se muestra número de entradas/salidas.','No puede deducirse acoplamiento.'],'Evolución temporal = dinámica.')
);

// 21. Estable y estacionario, ejemplo
add(
op('Estabilidad / estacionariedad','stable-stationary-motor','Motor operando alrededor de una velocidad constante','Da un ejemplo de un sistema estable y estacionario y argumenta.','Un motor operando con carga constante cuya velocidad permanece acotada alrededor de un valor fijo después del transitorio. Es estable porque no diverge y estacionario porque sus condiciones no cambian con el tiempo.',['Ejemplo concreto.','Argumenta estabilidad: respuesta acotada/no divergente.','Argumenta estacionariedad: propiedades/condiciones constantes en el tiempo.'],'Debes justificar ambas propiedades por separado.'),
op('Estabilidad / estacionariedad','stable-stationary-tank','Tanque operando en régimen permanente','Da un ejemplo estable y estacionario relacionado con nivel y argumenta.','Un tanque con caudal de entrada y salida constantes que mantiene el nivel alrededor de un valor fijo. La respuesta está acotada y las condiciones del sistema no cambian con el tiempo.',['Ejemplo.','Justificación de estabilidad.','Justificación de estacionariedad.'],'No basta con decir “no cambia”; explica acotamiento y constancia de parámetros.'),
op('Estabilidad / estacionariedad','stable-stationary-room','Habitación con temperatura regulada en condiciones constantes','Propón un sistema estable y estacionario y explica.','Una habitación con condiciones externas constantes y control que mantiene la temperatura acotada cerca del set-point. Es estable y sus parámetros/condiciones permanecen constantes: estacionario.',['Ejemplo pertinente.','Salida acotada.','Condiciones/propiedades invariantes en el tiempo.'],'Separa estabilidad de estacionariedad.'),
op('Estabilidad / estacionariedad','stable-stationary-speed','Banda transportadora a velocidad constante','Da un ejemplo de sistema estable y estacionario y argumenta ambos términos.','Una banda con carga y parámetros constantes cuya velocidad converge y permanece alrededor de un valor fijo. No diverge y el comportamiento del sistema no cambia con el tiempo.',['Ejemplo.','Acotamiento/convergencia.','Constancia temporal de las propiedades.'],'Dos propiedades, dos argumentos.')
);

// 22. Imagen -> planta/proceso/sistema
add(
mc('Planta / proceso / sistema','electric-scooter-system','Patín eléctrico con batería, motor y control','¿La imagen ilustra principalmente una planta, un proceso o un sistema?',['Planta aislada','Proceso','Sistema','Perturbación'],2,['La imagen destaca varios componentes relacionados, no solo un objeto aislado.','No muestra una secuencia de transformaciones.','Correcto: batería, motor, control y estructura cooperan para una función.','No es una influencia externa.'],'Aquí importa el conjunto de componentes trabajando juntos.'),
mc('Planta / proceso / sistema','refrigerator-system','Refrigerador con compresor, sensor y control','La imagen muestra varios componentes que cooperan para mantener temperatura. Representa un…',['Proceso','Sistema','Set-point','Error'],1,['Proceso sería el ciclo de refrigeración como secuencia.','Correcto: componentes coordinados con un objetivo.','No es una referencia.','No es una diferencia.'],'Conjunto coordinado + objetivo.'),
mc('Planta / proceso / sistema','drone-system','Dron con motores, batería, sensores y controlador','La imagen ilustra principalmente un…',['Sistema','Proceso','Planta únicamente','Señal'],0,['Correcto: varios componentes interactúan para mantener el vuelo.','Proceso sería la operación o secuencia.','No se enfatiza un único objeto pasivo.','No es información aislada.'],'Varios componentes cooperando.'),
mc('Planta / proceso / sistema','washer-system','Lavadora con motor, válvulas, sensores y control','La imagen muestra componentes que interactúan para realizar un ciclo completo. Es un…',['Proceso','Sistema','Referencia','Perturbación'],1,['Proceso sería llenar-lavar-enjuagar-centrifugar como secuencia.','Correcto: se enfatiza el conjunto de componentes.','No es valor deseado.','No es influencia externa.'],'Conjunto físico y lógico trabajando por un objetivo.')
);

// 23. Gráfico -> estabilidad
add(
mc('Interpretación gráfica','stable-converging','Oscilaciones decrecientes hacia la referencia','Según el gráfico, identifica el tipo de comportamiento del sistema.',['Inestable','Estable','Discreto','MISO'],1,['La amplitud no crece sin límite.','Correcto: la respuesta permanece acotada y converge.','La gráfica es continua en el tiempo.','No se muestra número de entradas.'],'Observa si las oscilaciones crecen o disminuyen.'),
mc('Interpretación gráfica','stable-overdamped','Respuesta que se aproxima a la referencia sin divergir','La respuesta mostrada corresponde a un sistema…',['Estable','Inestable','Desacoplado','MIMO'],0,['Correcto: permanece acotada y se aproxima al valor de referencia.','No diverge.','No se analiza acoplamiento.','No se muestran múltiples señales.'],'Acotado y convergente.'),
mc('Interpretación gráfica','unstable-growing','Oscilaciones de amplitud creciente','Según el gráfico, ¿cómo se clasifica el sistema?',['Estable','Inestable','Estático','SISO necesariamente'],1,['La respuesta crece y deja de estar acotada.','Correcto: las oscilaciones aumentan.','Se observa evolución temporal.','No se conoce toda la estructura de señales.'],'¿La respuesta permanece acotada?'),
mc('Interpretación gráfica','stable-damped','Respuesta amortiguada alrededor de la referencia','¿Qué propiedad ilustra la gráfica?',['Inestabilidad','Estabilidad','Aditividad','Desacoplamiento'],1,['No hay divergencia.','Correcto: la respuesta permanece acotada y las oscilaciones disminuyen.','No se están sumando entradas.','No se comparan subsistemas.'],'Oscilaciones decrecientes.')
);

// 24. Imagen -> proceso
add(
mc('Planta / proceso / sistema','crop-spray-process','Observar → decidir → actuar en fumigación','La secuencia ilustrada representa principalmente una planta, un proceso o un sistema?',['Planta','Proceso','Set-point','Perturbación'],1,['No se muestra solo el equipo físico.','Correcto: se muestran etapas sucesivas de una operación.','No es un valor deseado.','No es una influencia externa.'],'Varias etapas ordenadas = proceso.'),
mc('Planta / proceso / sistema','assembly-process','Ensamblar → inspeccionar → empacar','La imagen muestra etapas sucesivas de producción. Se clasifica principalmente como…',['Sistema','Proceso','Planta','Señal'],1,['Sistema sería el conjunto de máquinas y componentes.','Correcto: se enfatiza la secuencia de operaciones.','Planta sería el equipo físico.','No es una sola señal.'],'Se está mostrando qué ocurre paso a paso.'),
mc('Planta / proceso / sistema','water-treatment-process','Filtrar → desinfectar → almacenar','La secuencia ilustrada corresponde a un…',['Proceso','Planta','Actuador','Sensor'],0,['Correcto: son cambios/etapas sucesivas.','Planta sería la instalación de tratamiento.','No es un solo actuador.','No es un elemento de medición.'],'Etapas progresivas.'),
mc('Planta / proceso / sistema','baking-process','Mezclar → hornear → enfriar','¿Qué concepto describe mejor la secuencia ilustrada?',['Sistema','Proceso','Planta','Variable'],1,['Sistema sería el conjunto de equipos.','Correcto: se muestran transformaciones sucesivas.','Planta sería el equipo físico.','No es una magnitud.'],'Secuencia de cambios = proceso.')
);

// 25. Definición sistema de control
add(
mc('Sistema de control',none,'','Está definido como un conjunto de componentes que pueden regular su propia conducta o la de otro sistema con el fin de lograr un funcionamiento predeterminado. Se trata de un…',['Sistema de control','Proceso','Sistema manual','Sensor'],0,['Correcto.','Proceso es una sucesión de cambios.','Manual describe intervención humana.','Sensor es solo un componente.'],'La definición incluye regulación para lograr un funcionamiento deseado.'),
mc('Sistema de control',none,'','¿Qué concepto describe un conjunto de elementos que regula el comportamiento de un sistema para alcanzar una condición predeterminada?',['Sistema de control','Planta','Perturbación','Proceso'],0,['Correcto.','Planta es el objeto físico controlado.','Perturbación es una influencia externa.','Proceso es la transformación.'],'Regulación + objetivo predeterminado.'),
mc('Sistema de control',none,'','Un conjunto de componentes que mide, decide y actúa para lograr un comportamiento deseado es un…',['Proceso','Sistema de control','Sistema físico','Set-point'],1,['Proceso no implica necesariamente regulación.','Correcto.','Sistema físico es más general.','Set-point es solo la referencia.'],'El concepto incluye regulación.'),
mc('Sistema de control',none,'','Cuando varios componentes se organizan para hacer que otro sistema opere de una manera predeterminada, forman un…',['Sistema de control','Proceso continuo','Actuador','Sensor'],0,['Correcto.','No depende de que el tiempo sea continuo.','Actuador es solo una parte.','Sensor es solo una parte.'],'Conjunto que regula comportamiento.')
);

// 26. Definición sistemas físicos
add(
mc('Sistemas físicos',none,'','Son aquellos que se componen de elementos materiales y energéticos que interactúan entre sí para cumplir una función específica. Se llaman sistemas…',['Físicos','Abstractos','Discretos','MISO'],0,['Correcto: se basan en elementos materiales y energía.','Abstracto no describe componentes materiales.','Discreto es otra clasificación.','MISO se refiere a entradas/salidas.'],'Material + energía.'),
mc('Sistemas físicos',none,'','Un sistema formado por componentes materiales que intercambian energía para realizar una función es un sistema…',['Físico','Abstracto','Estacionario','Manual necesariamente'],0,['Correcto.','No está compuesto solo por conceptos o símbolos.','No se deduce estacionariedad.','Ser físico no implica manual.'],'Elementos materiales.'),
mc('Sistemas físicos',none,'','¿Cómo se clasifican los sistemas constituidos por elementos reales, materiales y energéticos que interactúan?',['Físicos','Lógicos','Discretos','Desacoplados'],0,['Correcto.','Lógico/abstracto no enfatiza materia y energía.','Otra clasificación.','Otra propiedad.'],'Piensa en existencia material.'),
mc('Sistemas físicos',none,'','Máquinas, tuberías, motores y fluidos que interactúan para cumplir una función forman un sistema de tipo…',['Físico','Abstracto','No estacionario necesariamente','MIMO necesariamente'],0,['Correcto.','No es únicamente conceptual.','No se deduce variación temporal.','No se conoce el número de señales.'],'Componentes materiales y energía.')
);

// 27. Figura -> variable controlada
add(
mc('Variable controlada','tank-level-control','Tanque con sensores de nivel, bomba y válvula','¿Qué variable se está controlando en la figura?',['Caudal de entrada','Nivel del líquido','Apertura de la válvula','Voltaje del panel'],1,['Puede ser una acción o condición de entrada, pero no el objetivo mostrado.','Correcto: los sensores alto/bajo y la lógica buscan mantener el nivel.','Es una acción del actuador.','No es la magnitud regulada mostrada.'],'¿Qué magnitud detectan los sensores y se desea mantener?'),
mc('Variable controlada','greenhouse-temp-control','Invernadero con sensor y calentador','En la figura, el controlador acciona el calentador para mantener una magnitud. ¿Cuál es la variable controlada?',['Potencia del calentador','Temperatura del invernadero','Apertura del contactor','Voltaje de alimentación'],1,['Es manipulada.','Correcto: es la magnitud que se desea mantener.','Es acción del actuador.','No es el objetivo del control.'],'La controlada es el resultado deseado.'),
mc('Variable controlada','motor-speed-control','Motor con encoder y controlador','¿Qué variable está siendo controlada en el sistema ilustrado?',['Voltaje aplicado','Velocidad del eje','Corriente del sensor','Ganancia del controlador'],1,['Es una posible variable manipulada.','Correcto: el encoder realimenta velocidad.','No es el objetivo principal.','Es un parámetro.'],'¿Qué magnitud se mide para comparar con la referencia?'),
mc('Variable controlada','pressure-control','Tubería con sensor de presión y válvula','La válvula se modifica para mantener constante una magnitud en la tubería. ¿Cuál es la variable controlada?',['Posición de la válvula','Presión','Señal de mando','Tiempo de apertura'],1,['Es manipulada.','Correcto.','Es la acción del controlador.','No es la magnitud regulada.'],'La controlada es el resultado que se desea mantener.')
);

// 28. Imagen -> lazo abierto/cerrado
add(
mc('Lazo abierto / cerrado','sensor-faucet','Llave automática activada por presencia de manos','¿El sistema ilustrado representa un lazo abierto o un lazo cerrado respecto al flujo de agua?',['Lazo cerrado','Lazo abierto','MISO','Estacionario'],1,['El sensor detecta manos, no realimenta el flujo de agua obtenido.','Correcto: la salida de agua no se mide para corregirse.','No se pregunta número de señales.','No es la clasificación relevante.'],'Que exista un sensor no significa automáticamente realimentación de la salida.'),
mc('Lazo abierto / cerrado','hand-dryer','Secador automático activado por presencia','Respecto al secado logrado, ¿el sistema de la imagen es lazo abierto o cerrado?',['Lazo abierto','Lazo cerrado','MIMO','Acoplado'],0,['Correcto: detecta presencia, pero no mide qué tan seca quedó la mano.','No realimenta la salida relevante.','No se pregunta entradas/salidas.','No se pregunta acoplamiento.'],'¿Mide el resultado del secado?'),
mc('Lazo abierto / cerrado','automatic-door','Puerta automática activada por detector de presencia','Si el detector solo decide abrir al detectar una persona y no mide la posición final de la puerta, el sistema mostrado es…',['Lazo cerrado','Lazo abierto','Estático','MISO'],1,['No hay realimentación de la salida “posición de puerta”.','Correcto.','La puerta cambia con el tiempo.','No es lo preguntado.'],'Sensor de presencia ≠ sensor de salida.'),
mc('Lazo abierto / cerrado','soap-dispenser','Dispensador automático por proximidad','El dispensador detecta la mano y entrega una dosis fija sin medir cuánto jabón salió realmente. Es…',['Lazo abierto','Lazo cerrado','SIMO','Desacoplado'],0,['Correcto: no realimenta la cantidad dispensada.','No corrige usando la salida real.','No se pregunta número de salidas.','No se analiza acoplamiento.'],'La salida no vuelve al controlador.')
);

// 29. Expresión matemática -> aditividad
add(
mc('Linealidad','additivity-expression','x₁(t)+x₂(t), u₁(t)+u₂(t) → y₁(t)+y₂(t)','¿Qué propiedad representa la expresión matemática mostrada?',['Proporcionalidad','Aditividad','Estabilidad','Estacionariedad'],1,['Proporcionalidad usa escalamiento por una constante.','Correcto: la respuesta a la suma es la suma de las respuestas.','No se habla de acotamiento.','No se habla de invariancia temporal.'],'Suma de entradas → suma de salidas.'),
mc('Linealidad','additivity-blocks','T[x₁+x₂] = T[x₁] + T[x₂]','¿Qué propiedad de linealidad representa la expresión?',['Aditividad','Homogeneidad','Estabilidad','Desacoplamiento'],0,['Correcto.','Homogeneidad usa T[a·x]=a·T[x].','Otra propiedad.','Otra clasificación.'],'La misma operación de suma aparece dentro y fuera del sistema.'),
mc('Linealidad','additivity-signals','u₁+u₂ produce y₁+y₂','Si la suma de dos entradas produce exactamente la suma de las respuestas individuales, ¿qué propiedad se verifica?',['Aditividad','Proporcionalidad','Estacionariedad','Lazo cerrado'],0,['Correcto.','Proporcionalidad se refiere a multiplicar por una constante.','No habla del tiempo.','No define realimentación.'],'Dos efectos por separado que se suman.'),
mc('Linealidad','additivity-expression-2','S{x₁+x₂}=S{x₁}+S{x₂}','La expresión ilustrada corresponde a la propiedad de…',['Estabilidad','Aditividad','Acoplamiento','Proporcionalidad'],1,['No trata acotamiento.','Correcto.','No trata interacción entre subsistemas.','La proporcionalidad usa un escalar.'],'Suma dentro del operador = suma de salidas.')
);

window.QUESTION_BANK=B[V];
if(window.QUESTION_BANK.length!==29) throw new Error('Cada versión debe contener exactamente 29 preguntas');
})();