import {createAssignedSession,watchSessions,redirectRun,downloadSessionData,deleteAssignedSession,cleanupExpiredFreeRuns} from './firebase-client.js';

document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="teacher-v21.css">');
const cfg=window.SUPPORT_METER_CONFIG,core=window.SupportMeterTeacherCore,firebaseCore=window.SupportMeterFirebaseCore,$=id=>document.getElementById(id);
const el={set:$('setNumber'),create:$('createSession'),sessions:$('sessionList'),download:$('downloadResults'),error:$('assignmentError'),share:$('shareBox'),link:$('studentLink'),copy:$('copyLink'),dot:$('monitorDot'),status:$('monitorStatus'),grid:$('studentGrid'),focusStage:$('focusStage'),focused:$('focusedStudent'),rail:$('thumbnailRail'),empty:$('emptyMonitor'),online:$('onlineCount'),total:$('totalCount'),hide:$('hideOffline')};
let catalog=[],active='all',runs={},focusId=null,hideOffline=false;
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const online=run=>run.status==='online'&&Date.now()-Number(run.lastSeen||0)<(cfg.onlineThresholdMs||40000);
const current=()=>catalog.find(item=>item.sessionId===active);
const studentUrl=item=>`${location.origin}/Connectivity5/Support-Meter/?join=${encodeURIComponent(item.joinToken)}`;
function status(ok,text){el.dot.className=`dot${ok?' live':''}`;el.status.textContent=text;}
function frame(run,n){const set=run.setNumber||Math.floor(Number(run.currentStory)/10)||1,story=Number(run.currentStory)%10||1;return `assets/stories-v16/set-${set}/story-${story}-frame-${n}.webp`;}
function sessionCard(item){const selected=item.sessionId===active,date=item.sessionType==='assigned'?new Date(Number(item.createdAt||Date.now())).toLocaleString():'';return `<button class="session-card${selected?' selected':''}" type="button" data-session-id="${esc(item.sessionId)}"><strong>${esc(item.title)}</strong><span class="session-count">${item.studentCount} student${item.studentCount===1?'':'s'} · <span class="session-live">${item.onlineCount} LIVE</span></span>${date?`<small>${esc(date)}</small>`:'<small>Independent practice</small>'}</button>`;}
function scrollSelectedSessionIntoView(){requestAnimationFrame(()=>{const selected=el.sessions.querySelector('.session-card.selected');if(!selected)return;const left=selected.offsetLeft,right=left+selected.offsetWidth,viewLeft=el.sessions.scrollLeft,viewRight=viewLeft+el.sessions.clientWidth;if(left<viewLeft)el.sessions.scrollTo({left,behavior:'smooth'});else if(right>viewRight)el.sessions.scrollTo({left:right-el.sessions.clientWidth,behavior:'smooth'});});}
function refreshSessionList(){const all=firebaseCore.visibleRuns(runs,'all',Date.now()),allItem={sessionId:'all',title:'ALL ACTIVE STUDENTS',studentCount:all.length,onlineCount:all.filter(online).length,sessionType:'all'};el.sessions.innerHTML=[allItem,...catalog.map(item=>({...item,title:item.sessionType==='free'?'FREE MODE':`SET ${item.setNumber}`}))].map(sessionCard).join('');const item=current();el.download.disabled=!item||item.sessionType==='free';el.share.classList.toggle('hidden',!item?.joinToken);if(item?.joinToken)el.link.value=studentUrl(item);}
function connectActive(){focusId=null;refreshSessionList();scrollSelectedSessionIntoView();render();status(true,'Live');}
function moveControls(run){const targets=catalog.filter(item=>item.sessionType==='assigned'&&item.sessionId!==run.sessionId);if(!targets.length)return '';return `<div class="move-tools" data-no-focus><select aria-label="Move ${esc(run.studentName)} to session">${targets.map(item=>`<option value="${esc(item.sessionId)}">Set ${item.setNumber}</option>`).join('')}</select><button type="button">Move</button></div>`;}
function card(run){
  const isOnline=online(run),result=run.latestResult||'waiting',node=document.createElement('article');node.className='student-card';node.tabIndex=0;node.dataset.id=run.id;node.setAttribute('role','button');node.setAttribute('aria-label',`${run.studentName}, ${run.storyTitle||'current activity'}`);
  node.innerHTML=`<div class="student-top"><div class="student-name">${esc(run.studentName)}</div><span class="${isOnline?'online-badge':'offline-badge'}">${isOnline?'● LIVE':run.status==='completed'?'COMPLETED':'OFFLINE'}</span></div>${Number(run.translationAttemptCount||0)>0?`<div class="translation-warning">⚠ TRANSLATION · ${Number(run.translationAttemptCount)} attempt${Number(run.translationAttemptCount)===1?'':'s'}</div>`:''}<div class="story-title">${esc(run.storyTitle||'Preparing story')} · ${run.storyProgress||1}/8</div><div class="story-summary">${esc(run.storySummary||run.lastAction||'Waiting for activity')}</div><div class="story-strip"><img src="${frame(run,1)}" alt="Scene 1"><img src="${frame(run,2)}" alt="Scene 2"><img src="${frame(run,3)}" alt="Scene 3"></div><div class="live-grid"><div class="live-item">Feeling<strong>${esc(run.liveFeeling||'—')}</strong></div><div class="live-item">Dialogue<strong>${esc(run.liveExpression||'—')}</strong></div><div class="live-item">Result<strong class="result-${esc(result)}">${esc(result)}</strong></div><div class="live-item">Attempt / Score<strong>${run.attempt||1} · ${run.score||0}</strong></div></div><div class="stats"><div><small>Support</small><strong>${run.supportMeter||0}%</strong></div><div><small>Score</small><strong>${run.score||0}</strong></div><div><small>Streak</small><strong>${run.streak||0}</strong></div></div>${moveControls(run)}`;
  const activate=()=>{focusId=core.toggleFocus(focusId,run.id);render();};node.addEventListener('click',event=>{if(!event.target.closest('[data-no-focus]'))activate();});node.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&!event.target.closest('[data-no-focus]')){event.preventDefault();activate();}});
  const controls=node.querySelector('.move-tools');if(controls)controls.querySelector('button').onclick=async()=>{const target=catalog.find(item=>item.sessionId===controls.querySelector('select').value);if(!target||!confirm(`${run.studentName} will lose current progress and restart Set ${target.setNumber}. Move this student?`))return;controls.querySelector('button').disabled=true;try{await redirectRun(run.id,target);}catch(error){showError(error.message||'Could not move the student.');}finally{controls.querySelector('button').disabled=false;}};
  return node;
}
function render(){const all=firebaseCore.visibleRuns(runs,active,Date.now()),visible=hideOffline?all.filter(online):all;el.grid.innerHTML='';el.focused.innerHTML='';el.rail.innerHTML='';if(focusId&&!visible.some(run=>run.id===focusId))focusId=null;if(focusId){el.focused.appendChild(card(visible.find(run=>run.id===focusId)));visible.filter(run=>run.id!==focusId).forEach(run=>el.rail.appendChild(card(run)));}else visible.forEach(run=>el.grid.appendChild(card(run)));el.grid.classList.toggle('hidden',Boolean(focusId));el.focusStage.classList.toggle('hidden',!focusId);el.empty.classList.toggle('hidden',visible.length>0);el.empty.textContent=active==='all'?'No active students are visible yet.':'No students have joined this session yet.';el.total.textContent=`${all.length} student${all.length===1?'':'s'}`;el.online.textContent=`${all.filter(online).length} online`;}
function showError(message){el.error.textContent=message;el.error.classList.remove('hidden');}
async function createSession(){el.error.classList.add('hidden');try{const created=await createAssignedSession(Number(el.set.value));active=created.sessionId;connectActive();}catch(error){console.error(error);showError('Could not create the session. Please try again.');}}
function csvRows(data){const rows=[];for(const [runId,responses] of Object.entries(data.responses||{})){const run=data.runs[runId]||{};for(const response of Object.values(responses||{}))rows.push({student_name:run.studentName,set_number:run.setNumber,story_id:response.storyId,story_title:response.storyTitle,selected_feeling:response.selectedFeeling,selected_expression:response.selectedExpression,feeling_correct:response.feelingCorrect,expression_correct:response.expressionCorrect,resolved:response.resolved,attempt:response.attempt,score:response.score,support_meter:response.supportMeter,created_at:new Date(response.createdAt).toISOString()});}return rows;}
async function downloadResults(){const item=current();if(!item||item.sessionType==='free')return;try{const data=await downloadSessionData(item.sessionId),blob=new Blob([core.buildCsv(csvRows(data))],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`support-meter-set-${item.setNumber}-${new Date().toISOString().slice(0,10)}.csv`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);if(!confirm('The results download has started. Delete this session, all student activity, and close its link now?'))return;await deleteAssignedSession(item.sessionId);active='all';connectActive();}catch(error){console.error(error);showError('Could not prepare or delete the session results.');}}
watchSessions(({sessions,runs:allRuns})=>{const previous=active;runs=allRuns;catalog=firebaseCore.normalizeSessions(sessions,runs,Date.now(),cfg.onlineThresholdMs||40000);if(previous!=='all'&&!catalog.some(item=>item.sessionId===previous))active='all';refreshSessionList();render();status(true,'Live');});
el.create.onclick=createSession;el.sessions.onclick=event=>{const button=event.target.closest('[data-session-id]');if(!button)return;active=button.dataset.sessionId;connectActive();};el.copy.onclick=async()=>{await navigator.clipboard.writeText(el.link.value);el.copy.textContent='Copied!';setTimeout(()=>el.copy.textContent='Copy Student Link',1400);};el.download.onclick=downloadResults;el.hide.onclick=()=>{hideOffline=!hideOffline;el.hide.textContent=hideOffline?'Show offline':'Hide offline';render();};
cleanupExpiredFreeRuns().catch(console.error);setInterval(()=>cleanupExpiredFreeRuns().catch(console.error),60000);render();
